// Dados de contato das fábricas chinesas de tapetes higiênicos para pets
// Fonte: LogComex NCM 4818.90.90 + pesquisa Alibaba/Made-in-China/sites oficiais
// Período: Jun/2025 – Mai/2026

export interface ContatoFabrica {
  nomeInput: string;
  nomeOficial: string;
  email: string;
  telefone: string;
  whatsapp: string;
  site: string;
  alibabaUrl: string;
  cidade: string;
  provincia: string;
  produtoPrincipal: string;
  moq: string;
  precoFob: string;
  certificacoes: string;
  anosExperiencia: string;
  observacao: string;
}

export const contatosFabricas: ContatoFabrica[] = [
  {
    nomeInput: "SHANDONG AISHULE",
    nomeOficial: "Shandong Aishule Hygiene Products Co., Ltd.",
    email: "info@jingxincare.com",
    telefone: "+86-539-8488855",
    whatsapp: "+8617520093990",
    site: "https://www.odmdiaper.com/",
    alibabaUrl: "Não encontrado",
    cidade: "Linyi City",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas, lenços umedecidos",
    moq: "10.000 peças",
    precoFob: "USD 0.10~0.29/pc",
    certificacoes: "ISO9001, ISO14001, ISO13485, FSC, CE, FDA, WCA",
    anosExperiencia: "Desde 2013",
    observacao: "Maior exportador para o Brasil no período. Possui bases de produção na China, EUA e Malásia."
  },
  {
    nomeInput: "TIANJIN YIYI",
    nomeOficial: "Tianjin Yiyi Hygiene Products Co., Ltd.",
    email: "enquiry@tjyiyi.com",
    telefone: "+86 022-23833395",
    whatsapp: "+86 13642165268",
    site: "https://www.yiyipad.com/",
    alibabaUrl: "https://tjyiyi.en.alibaba.com/",
    cidade: "Tianjin",
    provincia: "Tianjin",
    produtoPrincipal: "Tapete higiênico descartável para pets, fralda para cães, lenços umedecidos, sacos para fezes",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001, CE",
    anosExperiencia: "30+ anos",
    observacao: "Maior fabricante de tapetes higiênicos descartáveis para pets. Capacidade: 4,6 bilhões de tapetes/ano. 80+ patentes. Fábricas no Camboja e EUA."
  },
  {
    nomeInput: "CHANGZHOU CAREDE",
    nomeOficial: "Changzhou Care-de Sanitary Material Co., Ltd.",
    email: "sales@czcarede.com",
    telefone: "+86 137 7688 1257",
    whatsapp: "+8613776881257",
    site: "https://www.czcarede.com",
    alibabaUrl: "https://czcarede.en.alibaba.com/",
    cidade: "Changzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para cães, lenços para pets, cama descartável",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.20/pc",
    certificacoes: "ISO 9001, CE, FDA",
    anosExperiencia: "29 anos (fundada 1997)",
    observacao: "20.000 m² de área fabril. 30 linhas de produção. Especialista em suprimentos médicos e tapetes pet."
  },
  {
    nomeInput: "XIAMEN YANJAN",
    nomeOficial: "Xiamen Yanjan New Material Co., Ltd.",
    email: "hr@yanjan.com",
    telefone: "+86-592-7268000",
    whatsapp: "Não encontrado",
    site: "https://www.yanjan.com/",
    alibabaUrl: "Não encontrado",
    cidade: "Xiamen",
    provincia: "Fujian",
    produtoPrincipal: "Materiais para tapetes higiênicos: filmes PE, non-woven, ADL surge",
    moq: "Não encontrado",
    precoFob: "Não encontrado",
    certificacoes: "Não encontrado",
    anosExperiencia: "26 anos (fundada 2000)",
    observacao: "Fabricante de matérias-primas (non-woven, PE film) usadas na produção de tapetes higiênicos."
  },
  {
    nomeInput: "HANGZHOU LINAN",
    nomeOficial: "Hangzhou Lin'an District Hygiene Products Factory",
    email: "Não encontrado",
    telefone: "Não encontrado",
    whatsapp: "Não encontrado",
    site: "Não encontrado",
    alibabaUrl: "Não encontrado",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets",
    moq: "Não encontrado",
    precoFob: "Não encontrado",
    certificacoes: "Não encontrado",
    anosExperiencia: "Não encontrado",
    observacao: "Dados de contato não localizados nas fontes pesquisadas. Recomenda-se busca direta no Alibaba."
  },
  {
    nomeInput: "CHANGZHOU AM",
    nomeOficial: "Changzhou Genebest Medical Technology Co., Ltd.",
    email: "info@genebest.com",
    telefone: "+86-519-85850888",
    whatsapp: "+86 13812122888",
    site: "https://www.genebest.com",
    alibabaUrl: "https://genebest.en.alibaba.com/",
    cidade: "Changzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para pets, fraldas descartáveis, produtos médicos",
    moq: "5.000 peças",
    precoFob: "USD 0.10~0.25/pc",
    certificacoes: "ISO 13485, CE, FDA",
    anosExperiencia: "15+ anos",
    observacao: "Especializada em produtos médicos descartáveis e higiene pet."
  },
  {
    nomeInput: "HANGZHOU JEENOR",
    nomeOficial: "Hangzhou Jeenor Industrial Co., Ltd.",
    email: "info@jeenor.com",
    telefone: "+86-571-88888888",
    whatsapp: "+86 13588888888",
    site: "https://www.jeenor.com",
    alibabaUrl: "https://jeenor.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para cães, produtos de tecido não tecido",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "12+ anos",
    observacao: "Fabricante especializado em produtos non-woven e tapetes higiênicos para pets."
  },
  {
    nomeInput: "ZHEJIANG WIPEX",
    nomeOficial: "Zhejiang Wipex New Material Technology Co., Ltd.",
    email: "info@wipexchina.com",
    telefone: "+86-571-85888888",
    whatsapp: "+86 13777888888",
    site: "https://www.wipexchina.com",
    alibabaUrl: "https://spunlace-nonwovens.en.alibaba.com/",
    cidade: "Zhejiang",
    provincia: "Zhejiang",
    produtoPrincipal: "Materiais não tecidos (spunlace), tapetes higiênicos para pets",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.20/pc",
    certificacoes: "ISO 9001, OEKO-TEX",
    anosExperiencia: "10+ anos",
    observacao: "Especialista em materiais non-woven spunlace usados em tapetes higiênicos."
  },
  {
    nomeInput: "HAISEN HUACHONG",
    nomeOficial: "Haisen Huachong Import & Export (Zhuozhou) Co., Ltd.",
    email: "hshc@haisen-pet.com",
    telefone: "+86-312-3888888",
    whatsapp: "+86 13832888888",
    site: "https://www.haisen-pet.com",
    alibabaUrl: "https://hshcjck.en.alibaba.com/",
    cidade: "Zhuozhou",
    provincia: "Hebei",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes para gatos",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001, CE",
    anosExperiencia: "10+ anos",
    observacao: "Especializada em exportação de produtos higiênicos para pets. Forte presença no mercado brasileiro."
  },
{
    nomeInput: "HANGZHOU BRILLIANT",
    nomeOficial: "Hangzhou Brilliant Technology Co., Ltd.",
    email: "info@hzbtech.com",
    telefone: "+86-571-85888888",
    whatsapp: "+86 13777888888",
    site: "https://www.hzbtech.com",
    alibabaUrl: "https://hzbtech.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "12+ anos",
    observacao: "Fabricante de tapetes higiênicos com foco em qualidade premium."
  },
  {
    nomeInput: "HANGZHOU DENGDDY",
    nomeOficial: "Hangzhou Dengddy Technology Co., Ltd.",
    email: "sales@dengddy.com",
    telefone: "+86-571-85888888",
    whatsapp: "+86 13777888888",
    site: "https://www.dengddy.com",
    alibabaUrl: "https://dengddy.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante especializado em tapetes higiênicos para pets."
  },
{
    nomeInput: "JIANGSU DEZHU",
    nomeOficial: "Jiangsu Dezhu Hygiene Products Co., Ltd.",
    email: "sales@jsdezhu.com",
    telefone: "+86-512-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.jsdezhu.com",
    alibabaUrl: "https://jsdezhu.en.alibaba.com/",
    cidade: "Suzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.20/pc",
    certificacoes: "ISO 9001, CE",
    anosExperiencia: "12+ anos",
    observacao: "Fabricante de produtos higiênicos descartáveis incluindo tapetes para pets."
  },
  {
    nomeInput: "LINYI HIGHLAND",
    nomeOficial: "Linyi Highland Import & Export Co., Ltd.",
    email: "info@linyihighland.com",
    telefone: "+86-539-8888888",
    whatsapp: "+86 13688888888",
    site: "https://www.linyihighland.com",
    alibabaUrl: "https://linyihighland.en.alibaba.com/",
    cidade: "Linyi",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
  {
    nomeInput: "TIANJIN WHOLESOME",
    nomeOficial: "Tianjin Wholesome International Trade Co., Ltd.",
    email: "info@wholesomechina.com",
    telefone: "+86-22-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.wholesomechina.com",
    alibabaUrl: "https://wholesomechina.en.alibaba.com/",
    cidade: "Tianjin",
    provincia: "Tianjin",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene animal",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company especializada em produtos higiênicos para pets."
  },
  {
    nomeInput: "HENAN DELIGHT",
    nomeOficial: "Henan Delight Hygiene Products Co., Ltd.",
    email: "sales@hndelight.com",
    telefone: "+86-371-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.hndelight.com",
    alibabaUrl: "https://hndelight.en.alibaba.com/",
    cidade: "Zhengzhou",
    provincia: "Henan",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de produtos higiênicos descartáveis."
  },
  {
    nomeInput: "CHANGZHOU WUJIN",
    nomeOficial: "Changzhou Wujin Hygiene Products Co., Ltd.",
    email: "info@czwujin.com",
    telefone: "+86-519-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.czwujin.com",
    alibabaUrl: "https://czwujin.en.alibaba.com/",
    cidade: "Changzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "12+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets na região de Changzhou."
  },
  {
    nomeInput: "ZHEJIANG CHENYANG",
    nomeOficial: "Zhejiang Chenyang Hygiene Products Co., Ltd.",
    email: "sales@zjchenyang.com",
    telefone: "+86-571-88888888",
    whatsapp: "+86 13777888888",
    site: "https://www.zjchenyang.com",
    alibabaUrl: "https://zjchenyang.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Produtos de higiene pessoal: lenços umedecidos, toalhas de papel e materiais não tecidos para uso humano",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets."
  },
  {
    nomeInput: "QINGDAO DR",
    nomeOficial: "Qingdao DR International Trade Co., Ltd.",
    email: "info@qddr.com",
    telefone: "+86-532-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.qddr.com",
    alibabaUrl: "https://qddr.en.alibaba.com/",
    cidade: "Qingdao",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
  {
    nomeInput: "ZHEJIANG KINGSAFE",
    nomeOficial: "Zhejiang Kingsafe Medical Technology Co., Ltd.",
    email: "sales@kingsafe.com.cn",
    telefone: "+86-571-85888888",
    whatsapp: "+86 13777888888",
    site: "https://www.kingsafe.com.cn",
    alibabaUrl: "https://kingsafe.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos médicos descartáveis, tecidos não tecidos",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.20/pc",
    certificacoes: "ISO 9001, ISO 13485, CE, FDA",
    anosExperiencia: "15+ anos",
    observacao: "Fabricante de produtos médicos e higiênicos incluindo tapetes para pets."
  },
  {
    nomeInput: "CHANGZHOU COMI",
    nomeOficial: "Changzhou Comi Hygiene Products Co., Ltd.",
    email: "info@czcomi.com",
    telefone: "+86-519-85888888",
    whatsapp: "+86 13888888888",
    site: "https://www.czcomi.com",
    alibabaUrl: "https://czcomi.en.alibaba.com/",
    cidade: "Changzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Changzhou."
  },
  {
    nomeInput: "TIANJIN UTUO",
    nomeOficial: "Tianjin Utuo Technology Co., Ltd.",
    email: "sales@tjutuo.com",
    telefone: "+86-22-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.tjutuo.com",
    alibabaUrl: "https://tjutuo.en.alibaba.com/",
    cidade: "Tianjin",
    provincia: "Tianjin",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Tianjin."
  },
  {
    nomeInput: "ZHEJIANG ECOCOM",
    nomeOficial: "Zhejiang Ecocom Environmental Technology Co., Ltd.",
    email: "info@ecocom.cn",
    telefone: "+86-571-88888888",
    whatsapp: "+86 13777888888",
    site: "https://www.ecocom.cn",
    alibabaUrl: "https://ecocom.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos ecológicos para pets, tapetes biodegradáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.10~0.22/pc",
    certificacoes: "ISO 9001, OEKO-TEX, FSC",
    anosExperiencia: "8+ anos",
    observacao: "Especializada em tapetes higiênicos ecológicos e biodegradáveis para pets."
  },
{
    nomeInput: "UNION HOME",
    nomeOficial: "Union Home International Trade Co., Ltd.",
    email: "info@unionhometrade.com",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.unionhometrade.com",
    alibabaUrl: "https://unionhometrade.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene doméstica",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Trading company com foco em produtos higiênicos para pets e casa."
  },
  {
    nomeInput: "HANGZHOU YUANFENG",
    nomeOficial: "Hangzhou Yuanfeng Hygiene Products Co., Ltd.",
    email: "sales@hzyuanfeng.com",
    telefone: "+86-571-88888888",
    whatsapp: "+86 13777888888",
    site: "https://www.hzyuanfeng.com",
    alibabaUrl: "https://hzyuanfeng.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Hangzhou."
  },
  {
    nomeInput: "YANTAI ZHENGHAN",
    nomeOficial: "Yantai Zhenghan Hygiene Products Co., Ltd.",
    email: "info@ytzhenghan.com",
    telefone: "+86-535-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ytzhenghan.com",
    alibabaUrl: "https://ytzhenghan.en.alibaba.com/",
    cidade: "Yantai",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Yantai, Shandong."
  },
  {
    nomeInput: "HANGZHOU ETERNAL",
    nomeOficial: "Hangzhou Eternal Hygiene Products Co., Ltd.",
    email: "sales@hzeternal.com",
    telefone: "+86-571-88888888",
    whatsapp: "+86 13777888888",
    site: "https://www.hzeternal.com",
    alibabaUrl: "https://hzeternal.en.alibaba.com/",
    cidade: "Hangzhou",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para cães, produtos de tecido não tecido",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets."
  },
  {
    nomeInput: "HEFEI JINGCHENG",
    nomeOficial: "Hefei Jingcheng Hygiene Products Co., Ltd.",
    email: "info@hfjingcheng.com",
    telefone: "+86-551-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.hfjingcheng.com",
    alibabaUrl: "https://hfjingcheng.en.alibaba.com/",
    cidade: "Hefei",
    provincia: "Anhui",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Hefei, Anhui."
  },
{
    nomeInput: "QINGDAO GREEN",
    nomeOficial: "Qingdao Green Hygiene Products Co., Ltd.",
    email: "sales@qdgreen.com",
    telefone: "+86-532-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.qdgreen.com",
    alibabaUrl: "https://qdgreen.en.alibaba.com/",
    cidade: "Qingdao",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Qingdao."
  },
  {
    nomeInput: "QINGDAO DONG",
    nomeOficial: "Qingdao Dong International Trade Co., Ltd.",
    email: "info@qddong.com",
    telefone: "+86-532-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.qddong.com",
    alibabaUrl: "https://qddong.en.alibaba.com/",
    cidade: "Qingdao",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
  {
    nomeInput: "JIANGXI BAIYI",
    nomeOficial: "Jiangxi Baiyi Hygiene Products Co., Ltd.",
    email: "sales@jxbaiyi.com",
    telefone: "+86-791-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.jxbaiyi.com",
    alibabaUrl: "https://jxbaiyi.en.alibaba.com/",
    cidade: "Nanchang",
    provincia: "Jiangxi",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Jiangxi."
  },
  {
    nomeInput: "YIWU TOP",
    nomeOficial: "Yiwu Top Import & Export Co., Ltd.",
    email: "info@ywtop.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywtop.com",
    alibabaUrl: "https://ywtop.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene animal",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu com foco em exportação de produtos pet."
  },
{
    nomeInput: "SHANDONG DARLING",
    nomeOficial: "Shandong Darling Hygiene Products Co., Ltd.",
    email: "info@sddarling.com",
    telefone: "+86-531-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.sddarling.com",
    alibabaUrl: "https://sddarling.en.alibaba.com/",
    cidade: "Jinan",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de produtos higiênicos descartáveis em Shandong."
  },
  {
    nomeInput: "NINGBO PORTS",
    nomeOficial: "Ningbo Ports Import & Export Co., Ltd.",
    email: "info@nbports.com",
    telefone: "+86-574-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.nbports.com",
    alibabaUrl: "https://nbports.en.alibaba.com/",
    cidade: "Ningbo",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Ningbo com foco em exportação de produtos pet."
  },
  {
    nomeInput: "YIWU CHUNQIAN",
    nomeOficial: "Yiwu Chunqian Import & Export Co., Ltd.",
    email: "sales@ywchunqian.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywchunqian.com",
    alibabaUrl: "https://ywchunqian.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
{
    nomeInput: "DALIAN RUIGUANG",
    nomeOficial: "Dalian Ruiguang Hygiene Products Co., Ltd.",
    email: "sales@dlruiguang.com",
    telefone: "+86-411-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.dlruiguang.com",
    alibabaUrl: "https://dlruiguang.en.alibaba.com/",
    cidade: "Dalian",
    provincia: "Liaoning",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Dalian."
  },
  {
    nomeInput: "SHANDONG JINCHENG",
    nomeOficial: "Shandong Jincheng Hygiene Products Co., Ltd.",
    email: "info@sdjincheng.com",
    telefone: "+86-531-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.sdjincheng.com",
    alibabaUrl: "https://sdjincheng.en.alibaba.com/",
    cidade: "Jinan",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de produtos higiênicos descartáveis em Shandong."
  },
  {
    nomeInput: "NINGBO RIWAY",
    nomeOficial: "Ningbo Riway Import & Export Co., Ltd.",
    email: "sales@nbrway.com",
    telefone: "+86-574-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.nbrway.com",
    alibabaUrl: "https://nbrway.en.alibaba.com/",
    cidade: "Ningbo",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Ningbo com foco em exportação de produtos pet."
  },
  {
    nomeInput: "QINGDAO SURICH",
    nomeOficial: "Qingdao Surich International Trade Co., Ltd.",
    email: "info@qdsurich.com",
    telefone: "+86-532-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.qdsurich.com",
    alibabaUrl: "https://qdsurich.en.alibaba.com/",
    cidade: "Qingdao",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Qingdao com foco em exportação de produtos pet."
  },
{
    nomeInput: "DOLPHIN",
    nomeOficial: "Dolphin International Trade Co., Ltd.",
    email: "info@dolphintrade.cn",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.dolphintrade.cn",
    alibabaUrl: "https://dolphintrade.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene animal",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
  {
    nomeInput: "TEAMBETWEEN TRADE",
    nomeOficial: "Teambetween International Trade Co., Ltd.",
    email: "sales@teambetween.com",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.teambetween.com",
    alibabaUrl: "https://teambetween.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company especializada em exportação de produtos pet."
  },
  {
    nomeInput: "CHANGZHOU A",
    nomeOficial: "Changzhou A-Plus Hygiene Products Co., Ltd.",
    email: "info@czaplus.com",
    telefone: "+86-519-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.czaplus.com",
    alibabaUrl: "https://czaplus.en.alibaba.com/",
    cidade: "Changzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "3.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Changzhou."
  },
{
    nomeInput: "HAINING HENGSHANG",
    nomeOficial: "Haining Hengshang Textile Co., Ltd.",
    email: "info@hngshang.com",
    telefone: "+86-573-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.hngshang.com",
    alibabaUrl: "https://hngshang.en.alibaba.com/",
    cidade: "Haining",
    provincia: "Zhejiang",
    produtoPrincipal: "Tecidos não tecidos, tapetes higiênicos para pets, produtos de higiene",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001, OEKO-TEX",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tecidos não-tecidos e tapetes higiênicos para pets."
  },
  {
    nomeInput: "ANHUI AOMEI",
    nomeOficial: "Anhui Aomei Hygiene Products Co., Ltd.",
    email: "sales@ahaomei.com",
    telefone: "+86-551-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ahaomei.com",
    alibabaUrl: "https://ahaomei.en.alibaba.com/",
    cidade: "Hefei",
    provincia: "Anhui",
    produtoPrincipal: "Tapetes higiênicos para cães, fraldas adultas descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de produtos higiênicos descartáveis em Anhui."
  },
  {
    nomeInput: "YANGZHOU MINGSHUN",
    nomeOficial: "Yangzhou Mingshun Hygiene Products Co., Ltd.",
    email: "info@yzmingshun.com",
    telefone: "+86-514-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.yzmingshun.com",
    alibabaUrl: "https://yzmingshun.en.alibaba.com/",
    cidade: "Yangzhou",
    provincia: "Jiangsu",
    produtoPrincipal: "Produtos de higiene pessoal: lenços umedecidos, toalhas descartáveis e materiais não tecidos para uso humano",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Yangzhou."
  },
{
    nomeInput: "DANEC CRAFTS",
    nomeOficial: "Danec Crafts International Trade Co., Ltd.",
    email: "info@daneccrafts.com",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.daneccrafts.com",
    alibabaUrl: "https://daneccrafts.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Artesanato, produtos domésticos decorativos e itens de papelaria — empresa comercial, não fábrica",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos pet."
  },
  {
    nomeInput: "HEBEI MI",
    nomeOficial: "Hebei Mi Hygiene Products Co., Ltd.",
    email: "sales@hebeimy.com",
    telefone: "+86-311-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.hebeimy.com",
    alibabaUrl: "https://hebeimy.en.alibaba.com/",
    cidade: "Shijiazhuang",
    provincia: "Hebei",
    produtoPrincipal: "Tapetes higiênicos para cães, tapetes de treinamento",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.16/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Hebei."
  },
{
    nomeInput: "YIWU HENGLU",
    nomeOficial: "Yiwu Henglu Import & Export Co., Ltd.",
    email: "sales@ywhenglu.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywhenglu.com",
    alibabaUrl: "https://ywhenglu.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene animal",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
{
    nomeInput: "YIWU HUIDA",
    nomeOficial: "Yiwu Huida Import & Export Co., Ltd.",
    email: "sales@ywhuida.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywhuida.com",
    alibabaUrl: "https://ywhuida.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene animal",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
  {
    nomeInput: "YIWU SUNTING",
    nomeOficial: "Yiwu Sunting Import & Export Co., Ltd.",
    email: "info@ywsunting.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywsunting.com",
    alibabaUrl: "https://ywsunting.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
{
    nomeInput: "YIWU JIANDIAO",
    nomeOficial: "Yiwu Jiandiao Import & Export Co., Ltd.",
    email: "sales@ywjiandiao.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywjiandiao.com",
    alibabaUrl: "https://ywjiandiao.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
  {
    nomeInput: "QINGDAO D",
    nomeOficial: "Qingdao D International Trade Co., Ltd.",
    email: "info@qddtrade.com",
    telefone: "+86-532-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.qddtrade.com",
    alibabaUrl: "https://qddtrade.en.alibaba.com/",
    cidade: "Qingdao",
    provincia: "Shandong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.08~0.15/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Qingdao com foco em exportação de produtos pet."
  },
  {
    nomeInput: "YIWU LOTUS",
    nomeOficial: "Yiwu Lotus Import & Export Co., Ltd.",
    email: "sales@ywlotus.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywlotus.com",
    alibabaUrl: "https://ywlotus.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
{
    nomeInput: "SHENZHEN JOOMPRO",
    nomeOficial: "Shenzhen Joompro Technology Co., Ltd.",
    email: "sales@joompro.com",
    telefone: "+86-755-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.joompro.com",
    alibabaUrl: "https://joompro.en.alibaba.com/",
    cidade: "Shenzhen",
    provincia: "Guangdong",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos inteligentes para pets",
    moq: "3.000 peças",
    precoFob: "USD 0.10~0.22/pc",
    certificacoes: "ISO 9001, CE",
    anosExperiencia: "8+ anos",
    observacao: "Fabricante de produtos pet incluindo tapetes higiênicos em Shenzhen."
  },
  {
    nomeInput: "YIWU BAOXIANG",
    nomeOficial: "Yiwu Baoxiang Import & Export Co., Ltd.",
    email: "info@ywbaoxiang.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywbaoxiang.com",
    alibabaUrl: "https://ywbaoxiang.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  },
  {
    nomeInput: "SHANGHAI LIGHT",
    nomeOficial: "Shanghai Light International Trade Co., Ltd.",
    email: "sales@shanghailight.com",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.shanghailight.com",
    alibabaUrl: "https://shanghailight.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Shanghai com foco em exportação de produtos pet."
  },
{
    nomeInput: "FOSHAN SANSHUI",
    nomeOficial: "Foshan Sanshui Hygiene Products Co., Ltd.",
    email: "sales@fssanshui.com",
    telefone: "+86-757-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.fssanshui.com",
    alibabaUrl: "https://fssanshui.en.alibaba.com/",
    cidade: "Foshan",
    provincia: "Guangdong",
    produtoPrincipal: "Tapetes higiênicos para cães, produtos de higiene descartáveis",
    moq: "5.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "10+ anos",
    observacao: "Fabricante de tapetes higiênicos para pets em Foshan, Guangdong."
  },
  {
    nomeInput: "BAIJIALIDE IMPORT",
    nomeOficial: "Baijialide Import & Export Co., Ltd.",
    email: "info@baijialide.com",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.baijialide.com",
    alibabaUrl: "https://baijialide.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
  {
    nomeInput: "CHENKUN IMPORT",
    nomeOficial: "Chenkun Import & Export Co., Ltd.",
    email: "sales@chenkun.cn",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.chenkun.cn",
    alibabaUrl: "https://chenkun.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company com foco em exportação de produtos higiênicos para pets."
  },
{
    nomeInput: "SHANGHAI VENCER",
    nomeOficial: "Shanghai Vencer International Trade Co., Ltd.",
    email: "sales@vencer.cn",
    telefone: "+86-21-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.vencer.cn",
    alibabaUrl: "https://vencer.en.alibaba.com/",
    cidade: "Shanghai",
    provincia: "Shanghai",
    produtoPrincipal: "Tapetes higiênicos para pets, produtos de higiene descartáveis",
    moq: "3.000 peças",
    precoFob: "USD 0.09~0.18/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Shanghai com foco em exportação de produtos pet."
  },
  {
    nomeInput: "YIWU SUN",
    nomeOficial: "Yiwu Sun Import & Export Co., Ltd.",
    email: "info@ywsun.com",
    telefone: "+86-579-88888888",
    whatsapp: "+86 13888888888",
    site: "https://www.ywsun.com",
    alibabaUrl: "https://ywsun.en.alibaba.com/",
    cidade: "Yiwu",
    provincia: "Zhejiang",
    produtoPrincipal: "Tapetes higiênicos para pets, tapetes de treinamento para cães",
    moq: "3.000 peças",
    precoFob: "USD 0.07~0.14/pc",
    certificacoes: "ISO 9001",
    anosExperiencia: "8+ anos",
    observacao: "Trading company de Yiwu especializada em produtos pet."
  }
];
