// =============================================================
// DADOS REAIS - IMPORTACAO DE TAPETES HIGIENICOS PARA CAES
// Fonte: LogComex NCM 4818.90.90 (Jan-Mar/2026) + Alibaba/Made-in-China
// =============================================================

export const logcomexStats = {
  ncm: "4818.90.90",
  periodo: "Jun/2025 - Mai/2026 (12 meses)",
  valorTotalFobUsd: 28120333,
  pesoTotalKg: 13457056,
  precoMedioUsdPorKg: 2.09,
  totalExportadores: 81,
  totalImportadores: 64,
  totalMarcas: 87,
  totalModelos: 227,
  totalOperacoes: 2856,
  paisesOrigem: 1,
  estadosImportadores: 19,
  cidadesImportadores: 142,
  modalPredominante: "Maritimo",
};

export const topEstadosImportadores = [
  { estado: "SC", operacoes: 308 },
  { estado: "SP", operacoes: 252 },
  { estado: "PR", operacoes: 65 },
  { estado: "AL", operacoes: 55 },
  { estado: "RO", operacoes: 26 },
  { estado: "MG", operacoes: 15 },
  { estado: "RJ", operacoes: 14 },
  { estado: "RS", operacoes: 12 },
];

export const topCidadesImportadores = [
  { cidade: "Aruja (SP)", pesoKg: 870160 },
  { cidade: "Itajai (SC)", pesoKg: 537275 },
  { cidade: "Imbituba (SC)", pesoKg: 453636 },
  { cidade: "Maceio (AL)", pesoKg: 331412 },
  { cidade: "Curitiba (PR)", pesoKg: 257307 },
  { cidade: "Sao Paulo (SP)", pesoKg: 210366 },
  { cidade: "Criciuma (SC)", pesoKg: 175573 },
  { cidade: "Porto Velho (RO)", pesoKg: 94330 },
];

export const topExportadores = [
  {
    nome: "Shandong Aishule Hygiene Products Co., Ltd.",
    nomeLogcomex: "SHANDONG AISHULE CHINA",
    provincia: "Shandong",
    fobUsd: 2585917,
    percentual: 35.27,
    pesoKg: 843879,
    marcas: ["SHANDONG AISHULE HYGIENE"],
    relevancia: "top" as const,
  },
  {
    nome: "Tianjin Yiyi Hygiene Products Co., Ltd.",
    nomeLogcomex: "TIANJIN YIYI CHINA",
    provincia: "Tianjin",
    fobUsd: 510058,
    percentual: 6.96,
    pesoKg: 297969,
    marcas: ["HUSHPET", "SANCLEAN", "HUSPET"],
    relevancia: "top" as const,
  },
  {
    nome: "Care-De (Changzhou) Hygiene Products Co., Ltd.",
    nomeLogcomex: "CHANGZHOU CAREDE CHINA",
    provincia: "Jiangsu",
    fobUsd: 393882,
    percentual: 5.37,
    pesoKg: 189621,
    marcas: ["CAREDE"],
    relevancia: "top" as const,
  },
  {
    nome: "Xiamen Yanjan Daily Necessities Co., Ltd.",
    nomeLogcomex: "XIAMEN YANJAN CHINA",
    provincia: "Fujian",
    fobUsd: 361435,
    percentual: 4.93,
    pesoKg: 235071,
    marcas: ["YANJAN"],
    relevancia: "top" as const,
  },
  {
    nome: "Hangzhou Linan Hygiene Products Co., Ltd.",
    nomeLogcomex: "HANGZHOU LINAN CHINA",
    provincia: "Zhejiang",
    fobUsd: 298000,
    percentual: 4.06,
    pesoKg: 150000,
    marcas: ["LINAN"],
    relevancia: "top" as const,
  },
];

export const todosExportadores = [
  { nome: "SHANDONG AISHULE CHINA", pais: "China", provincia: "Shandong", relevancia: "top" },
  { nome: "TIANJIN YIYI CHINA", pais: "China", provincia: "Tianjin", relevancia: "top" },
  { nome: "CHANGZHOU CAREDE CHINA", pais: "China", provincia: "Jiangsu", relevancia: "top" },
  { nome: "XIAMEN YANJAN CHINA", pais: "China", provincia: "Fujian", relevancia: "top" },
  { nome: "HANGZHOU LINAN CHINA", pais: "China", provincia: "Zhejiang", relevancia: "top" },
  { nome: "CHANGZHOU AM CHINA", pais: "China", provincia: "Jiangsu", relevancia: "alto" },
  { nome: "HANGZHOU JEENOR CHINA", pais: "China", provincia: "Zhejiang", relevancia: "alto" },
  { nome: "ZHEJIANG WIPEX CHINA", pais: "China", provincia: "Zhejiang", relevancia: "alto" },
  { nome: "HAISEN HUACHONG CHINA", pais: "China", provincia: "Nao identificada", relevancia: "alto" },
{ nome: "HANGZHOU BRILLIANT CHINA", pais: "China", provincia: "Zhejiang", relevancia: "alto" },
  { nome: "HANGZHOU DENGDDY CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "JIANGSU DEZHU CHINA", pais: "China", provincia: "Jiangsu", relevancia: "medio" },
  { nome: "LINYI HIGHLAND CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "TIANJIN WHOLESOME CHINA", pais: "China", provincia: "Tianjin", relevancia: "medio" },
  { nome: "HENAN DELIGHT CHINA", pais: "China", provincia: "Henan", relevancia: "medio" },
  { nome: "CHANGZHOU WUJIN CHINA", pais: "China", provincia: "Jiangsu", relevancia: "medio" },
  { nome: "ZHEJIANG CHENYANG CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "QINGDAO DR CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "ZHEJIANG KINGSAFE CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "CHANGZHOU COMI CHINA", pais: "China", provincia: "Jiangsu", relevancia: "medio" },
  { nome: "TIANJIN UTUO CHINA", pais: "China", provincia: "Tianjin", relevancia: "medio" },
  { nome: "ZHEJIANG ECOCOM CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "UNION HOME CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
  { nome: "HANGZHOU YUANFENG CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "YANTAI ZHENGHAN CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "HANGZHOU ETERNAL CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "HEFEI JINGCHENG CHINA", pais: "China", provincia: "Anhui", relevancia: "medio" },
{ nome: "QINGDAO GREEN CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "QINGDAO DONG CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "JIANGXI BAIYI CHINA", pais: "China", provincia: "Jiangxi", relevancia: "medio" },
  { nome: "YIWU TOP CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "SHANDONG DARLING CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "NINGBO PORTS CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "YIWU CHUNQIAN CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "DALIAN RUIGUANG CHINA", pais: "China", provincia: "Liaoning", relevancia: "medio" },
  { nome: "SHANDONG JINCHENG CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "NINGBO RIWAY CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "QINGDAO SURICH CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
{ nome: "DOLPHIN CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
  { nome: "TEAMBETWEEN TRADE CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
  { nome: "CHANGZHOU A CHINA", pais: "China", provincia: "Jiangsu", relevancia: "medio" },
{ nome: "HAINING HENGSHANG CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "ANHUI AOMEI CHINA", pais: "China", provincia: "Anhui", relevancia: "medio" },
  { nome: "YANGZHOU MINGSHUN CHINA", pais: "China", provincia: "Jiangsu", relevancia: "medio" },
{ nome: "DANEC CRAFTS CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
  { nome: "HEBEI MI CHINA", pais: "China", provincia: "Hebei", relevancia: "medio" },
{ nome: "YIWU HENGLU CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "YIWU HUIDA CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "YIWU SUNTING CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "YIWU JIANDIAO CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "QINGDAO D CHINA", pais: "China", provincia: "Shandong", relevancia: "medio" },
  { nome: "YIWU LOTUS CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
{ nome: "SHENZHEN JOOMPRO CHINA", pais: "China", provincia: "Guangdong", relevancia: "medio" },
  { nome: "YIWU BAOXIANG CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "SHANGHAI LIGHT CHINA", pais: "China", provincia: "Shanghai", relevancia: "medio" },
{ nome: "FOSHAN SANSHUI CHINA", pais: "China", provincia: "Guangdong", relevancia: "medio" },
  { nome: "BAIJIALIDE IMPORT CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
  { nome: "CHENKUN IMPORT CHINA", pais: "China", provincia: "Nao identificada", relevancia: "medio" },
{ nome: "SHANGHAI VENCER CHINA", pais: "China", provincia: "Shanghai", relevancia: "medio" },
  { nome: "YIWU SUN CHINA", pais: "China", provincia: "Zhejiang", relevancia: "medio" },
  { nome: "TOMS TOY HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "KAYLONG MONTES HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "BRIGHT DX HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "JP GRUPPE FELLBACH HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "PHOENIX SOURCING HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "SMART HORSE HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "AXIS RAY HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "MERCOSUL HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "SWITH INDUSTRY HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "PREMIUM SOURCE HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "DEVELOPMENT HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "INOVE TRADE HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "MOUNTAINKING HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "YIWU ZBT HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "TOP CENTURY HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "XCAPE TRADING HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "JC MR CHINA HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "TK GLOBAL CHINA HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "BBA HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "HK ZENITHWAY DIGITAL TECHNOLOGY HONG KONG", pais: "Hong Kong", provincia: "Hong Kong", relevancia: "medio" },
  { nome: "COLOMBIANA KIMBERLY COLOMBIA", pais: "Colombia", provincia: "-", relevancia: "baixo" },
  { nome: "CEDRS HOSPITALAR UNITED STATES", pais: "EUA", provincia: "-", relevancia: "baixo" },
  { nome: "CARREFOUR IMPORT FRANCE", pais: "Franca", provincia: "-", relevancia: "baixo" },
  { nome: "ESSITY PRO UNITED STATES", pais: "EUA", provincia: "-", relevancia: "baixo" },
  { nome: "DAISO INDUSTRIES JAPAN", pais: "Japao", provincia: "-", relevancia: "baixo" },
  { nome: "SGP URUGUAY", pais: "Uruguai", provincia: "-", relevancia: "baixo" },
  { nome: "SAGRIN URUGUAY", pais: "Uruguai", provincia: "-", relevancia: "baixo" },
  { nome: "EURONDA ITALY", pais: "Italia", provincia: "-", relevancia: "baixo" },
  { nome: "IMARKETKOREA SOUTH KOREA", pais: "Coreia do Sul", provincia: "-", relevancia: "baixo" },
  { nome: "FUJI JAPAN", pais: "Japao", provincia: "-", relevancia: "baixo" },
  { nome: "ESSITY NETHERLANDS", pais: "Holanda", provincia: "-", relevancia: "baixo" },
  { nome: "TESA SE GERMANY", pais: "Alemanha", provincia: "-", relevancia: "baixo" },
  { nome: "CELLULOSE CONVERTING ITALY", pais: "Italia", provincia: "-", relevancia: "baixo" },
  { nome: "TTS CLEANING ITALY", pais: "Italia", provincia: "-", relevancia: "baixo" },
  { nome: "SIEMENS ENERGY SWEDEN", pais: "Suecia", provincia: "-", relevancia: "baixo" },
  { nome: "SPGPRINTS AUSTRIA", pais: "Austria", provincia: "-", relevancia: "baixo" },
  { nome: "POWERCOM ELECTRONICS TAIWAN", pais: "Taiwan", provincia: "-", relevancia: "baixo" },
  { nome: "CATERPILLAR SARL SWITZERLAND", pais: "Suica", provincia: "-", relevancia: "baixo" },
  { nome: "MABUCHI ST JAPAN", pais: "Japao", provincia: "-", relevancia: "baixo" },
  { nome: "PRODUTOS FAMILIA COLOMBIA", pais: "Colombia", provincia: "-", relevancia: "baixo" },
];

export const topImportadores = [
  { nome: "BM3 IMPORTACAO E EXPORTACAO LTDA", fobUsd: 2638553, percentual: 35.99, pesoKg: 870294, estado: "SP", cidade: "Aruja" },
  { nome: "LALA PET IMPORT LTDA", fobUsd: 559204, percentual: 7.63, pesoKg: 331412, estado: "AL", cidade: "Maceio" },
  { nome: "PETGLOBAL IMPORTACAO E COMERCIO DE PRODUTOS PARA ANIMAIS LTDA", fobUsd: 427522, percentual: 5.83, pesoKg: 205308, estado: "SC", cidade: "Imbituba" },
  { nome: "UNIPET DISTRIBUIDORA DE PRODUTOS AGROPECUARIOS LTDA", fobUsd: 298139, percentual: 4.07, pesoKg: 175560, estado: "SC", cidade: "Itajai" },
  { nome: "HIGIEFARM - COMERCIO, IMPORTACAO E EXPORTACAO LTDA", fobUsd: 277050, percentual: 3.78, pesoKg: 177427, estado: "SC", cidade: "Itajai" },
];

export const todosImportadores = [
  "BM3 IMPORTACAO E EXPORTACAO LTDA",
  "LALA PET IMPORT LTDA",
  "PETGLOBAL IMPORTACAO E COMERCIO DE PRODUTOS PARA ANIMAIS LTDA",
  "UNIPET DISTRIBUIDORA DE PRODUTOS AGROPECUARIOS LTDA",
  "HIGIEFARM - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
  "INOVEN INDUSTRIA, COMERCIO E IMPORTACAO LTDA",
  "MEC G STORE IMPORTS LTDA",
  "M HAMEED COMERCIO DE PRODUTOS DE BELEZA E BARBEARIA",
  "TEQLA COMERCIO E SUPRIMENTOS LTDA",
  "HOSPFLEX EMBALAGENS LTDA",
  "ESSITY DO BRASIL INDUSTRIA E COMERCIO LTDA",
  "MULTI-MARCAS INDUSTRIA DE PRODUTOS HIGIENICOS LTDA",
  "NORDSTROM COMERCIAL LTDA",
  "BOMA COMERCIO LTDA.",
  "FELIPE SIELSKI ROMUALDO DE OLIVEIRA COMERCIO VAREJISTA",
  "MELO PET SHOP - COMERCIO DE RACOES LTDA",
  "CONNECTA IMPORTACAO E EXPORTACAO LTDA",
  "SUDAMERICA TRADING LTDA",
  "AGORA 2 GO IMPORTACAO E EXPORTACAO LTDA",
  "COMERCIAL BRASIL ATACADISTA DE PRODUTOS ALIMENTICIOS LTDA",
  "THCR COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
  "SUPERIA TRADING LTDA",
  "MUNDORA IMPORTACAO E DISTRIBUICAO LTDA",
  "STERILEX CIENTIFICA LTDA",
  "RICA COMERCIO E SERVICOS LTDA.",
  "GARRA ANIMAL COMERCIO ATACADISTA DE MEDICAMENTOS E DROGAS DE USO VETERINARIO LTDA",
  "MJK IMPORTACAO, EXPORTACAO E REPRESENTACAO LTDA.",
  "DAISO BRASIL COMERCIO E IMPORTACAO LTDA.",
  "SENIOR COMERCIAL, IMPORTACAO E DISTRIBUICAO LTDA",
  "PRIME OFFICE LTDA",
  "ALWAYS COMERCIAL IMPORTADORA LTDA",
  "MEX TRADE IMPORTADORA E EXPORTADORA LTDA",
  "FCM COMERCIO DE MIUDEZAS LTDA",
  "ROJEMAC IMPORTACAO E EXPORTACAO LIMITADA",
  "NAPI IMPORT IMPORTACAO E EXPORTACAO LTDA",
  "NT FLEX INDUSTRIA E COMERCIO DE ARTIGOS DE TOUCADOR E HIGIENE LTDA",
  "PRONTO IMPORT LTDA",
  "HGS COMEX LTDA.",
  "TRL INTERNACIONAL, IMPORTADORA E EXPORTADORA LTDA",
  "W A COMERCIO E DISTRIBUICAO LTDA",
  "VMN BRASIL COMERCIO E DISTRIBUIDORA LTDA",
  "TURIN TRADING IMPORTACAO E EXPORTACAO LTDA",
  "COPA INDUSTRIAL LTDA",
  "MEGA E-COMMERCE LTDA",
  "FLAMARIMPEX - REPRESENTACOES COMERCIAIS LTDA",
  "WHF INDUSTRIA IMPORTACAO E EXPORTACAO LTDA",
  "IGMA COMERCIO SERVICOS E MANUTENCAO LTDA",
  "MINASUL COMPANHIA GERAL DE PRODUTOS LTDA",
  "CROSS CONTINENTAL TRADING LTDA",
  "LEVE MAIS ATACADISTA LTDA",
  "COSTA DISTRIBUIDORA E COMERCIO INTERNACIONAL LTDA",
  "AVANTE COMERCIO DE PRODUTOS EM GERAL LTDA",
  "ELEVEN COMERCIO LTDA",
  "LUXOR COMERCIO INTERNACIONAL LTDA",
  "MARGARETH BERTONI GHUNEIM LTDA",
  "LDX COMERCIO E IMPORTACAO LTDA",
  "PREMIER TRADE COMERCIO IMPORTACAO E EXPORTACAO LTDA",
  "CARAVAN DO BRASIL TRADING LTDA",
  "LION IMPORT COMERCIO, IMPORTACAO E EXPORTACAO LTDA.",
  "ALPHA YNFINITY COMERCIO INTERNACIONAL LTDA",
  "FLASH IMPORTADORA, COMERCIO ATACADISTA DE VARIEDADES LTDA",
  "DALE LOG COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
  "GENESIS IMPORTS COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
  "DROMOS COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
  "ALIANCA COMERCIO ATACADISTA LTDA",
  "SLIME IMPORT LTDA",
  "20 COMERCIAL DE UTILIDADES DOMESTICAS LTDA",
  "BRAKEY COMERCIO DE PRODUTOS DE HIGIENE LTDA",
  "BRING IMPORT LTDA",
  "D&A DECORACAO E AMBIENTACAO LTDA",
  "CASARAO DO E-COMMERCE LTDA",
  "CLINK COMERCIO DE IMPORTACAO E EXPORTACAO LTDA",
  "H & W TRADING IMPORTACAO E EXPORTACAO LTDA",
  "UPPER TRADE IMPORTACAO E EXPORTACAO LTDA",
  "DE MACEDO FONSECA LTDA",
  "NOVO SECULO IMPORTACAO EXPORTACAO E COMERCIO LTDA",
  "DM8 COMERCIO E SERVICOS LTDA",
  "DOMESTIX COMERCIO LTDA",
  "MRD IMPORTACAO E EXPORTACAO LTDA",
  "DJW COMERCIO, IMPORTACAO E EXPORTACAO LTDA.",
  "BUENO IMPORTADORA E EXPORTADORA LTDA",
  "SECCON INDUSTRIA COMERCIO LTDA.",
  "FONTEBRAS COMERCIO DE PRESENTES LTDA",
  "JRF IMPORTS COMERCIAL LTDA",
  "ASN BRASIL IMPORTACAO E EXPORTACAO LTDA",
  "NEPTUNE 8 IMPORTACAO E EXPORTACAO LTDA",
  "T. GLOBO IMPORTACAO E EXPORTACAO LTDA",
  "TRAIDEX - COMERCIO IMPORTACAO E EXPORTACAO LTDA",
  "LIVE LASH IMPORTACAO LTDA",
  "CURY COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
  "MAXIMO IMPORTACAO E EXPORTACAO LTDA",
  "BBI DISTRIBUIDORA DE ARTIGOS DIVERSOS LTDA",
  "TOTALL VERSE IMPORTACAO E COMERCIO LTDA",
  "EURO-X IMPORTACAO & EXPORTACAO LTDA",
  "OPEN TRADE EXPORTACAO E IMPORTACAO LTDA",
  "RLG DO BRASIL DISTRIBUICAO E VAREJO LTDA",
  "RDR IMPORTACAO E EXPORTACAO LTDA",
  "AZUL IMPORTACAO LTDA",
  "TRANSO COMERCIO E IMPORTACAO LTDA",
];

export const marcas = [
  { marca: "PAPER", tipo: "Generica", origem: "China" },
  { marca: "HUSPET / HUSHPET", tipo: "Pet", origem: "China", fabricante: "Tianjin Yiyi" },
  { marca: "SHANDONG AISHULE HYGIENE", tipo: "Fabricante", origem: "China" },
  { marca: "SEM MARCA", tipo: "Sem marca", origem: "China" },
  { marca: "SWITH INDUSTRY", tipo: "Trading", origem: "Hong Kong" },
  { marca: "POWERMAX", tipo: "Pet", origem: "China" },
  { marca: "READY SEC", tipo: "Higiene", origem: "China" },
  { marca: "UNIFLEX", tipo: "Higiene", origem: "China" },
  { marca: "MSA", tipo: "Generica", origem: "EUA" },
  { marca: "MUSTACHE COR", tipo: "Pet", origem: "China" },
  { marca: "GOLEX", tipo: "Pet", origem: "China" },
  { marca: "GOLEX COR", tipo: "Pet", origem: "China" },
  { marca: "HYPERDRY", tipo: "Pet", origem: "China" },
  { marca: "FISHER SCIENTIFIC", tipo: "Cientifica", origem: "EUA" },
  { marca: "FRATELLI", tipo: "Pet", origem: "China" },
  { marca: "HOSPFLEX", tipo: "Hospitalar", origem: "Brasil" },
  { marca: "ULINE", tipo: "Distribuicao", origem: "EUA" },
  { marca: "AMBIENTE", tipo: "Pet", origem: "Brasil" },
  { marca: "CARREFOUR", tipo: "Varejo", origem: "Franca" },
  { marca: "FUJI", tipo: "Generica", origem: "Japao" },
  { marca: "PET GLOBAL", tipo: "Pet", origem: "Brasil" },
  { marca: "PELO AMOR", tipo: "Pet", origem: "Brasil" },
  { marca: "DEYI HYGIENE", tipo: "Higiene", origem: "China" },
  { marca: "CARTIER", tipo: "Pet", origem: "China" },
  { marca: "BARBERMIX COR", tipo: "Pet", origem: "China" },
  { marca: "LIGHT", tipo: "Generica", origem: "China" },
  { marca: "POWERMAID", tipo: "Pet", origem: "China" },
  { marca: "MASTACHE COR", tipo: "Pet", origem: "China" },
  { marca: "DAISO", tipo: "Varejo", origem: "Japao" },
  { marca: "JIANICAT", tipo: "Pet", origem: "China" },
  { marca: "SANCLEAN", tipo: "Higiene", origem: "China" },
  { marca: "ELINTREE", tipo: "Pet", origem: "China" },
  { marca: "NEWCLEARS", tipo: "Pet", origem: "China" },
  { marca: "KINGSAFE", tipo: "Pet", origem: "China" },
  { marca: "WIPEX", tipo: "Higiene", origem: "China" },
  { marca: "JEENOR", tipo: "Pet", origem: "China" },
  { marca: "DENGDDY", tipo: "Pet", origem: "China" },
  { marca: "BRILLIANT", tipo: "Pet", origem: "China" },
  { marca: "CAREDE", tipo: "Pet", origem: "China" },
];

export const fabricantesDetalhados = [
  { id: 1, nome: "Shandong Aishule Hygiene Products Co., Ltd.", nomeLogcomex: "SHANDONG AISHULE CHINA", localizacao: "Shandong, China", provincia: "Shandong", fobUsd: 2585917, percentualMercado: 35.27, pesoKg: 843879, relevancia: "top", especialidade: "Tapetes higienicos para pets, fraldas descartaveis", marcas: ["SHANDONG AISHULE HYGIENE"], site: "https://www.aishule.com", certificacoes: ["ISO 9001", "CE", "SGS"], descricao: "Maior exportador individual para o Brasil no NCM 4818.90.90, com 35% do volume total." },
  { id: 2, nome: "Tianjin Yiyi Hygiene Products Co., Ltd.", nomeLogcomex: "TIANJIN YIYI CHINA", localizacao: "Zhangjiawo Industrial Park, Tianjin, China", provincia: "Tianjin", fobUsd: 510058, percentualMercado: 6.96, pesoKg: 297969, relevancia: "top", especialidade: "Pet Pads, Dog Diapers, Pet Wipes, Poop Bags", marcas: ["HUSHPET", "SANCLEAN", "HUSPET"], site: "https://www.yiyipad.com", contato: "enquiry@tjyiyi.com | +86 022-23833395", certificacoes: ["ISO", "CE", "SGS"], descricao: "Um dos maiores fabricantes de tapetes higienicos para pets da China." },
  { id: 3, nome: "Care-De (Changzhou) Hygiene Products Co., Ltd.", nomeLogcomex: "CHANGZHOU CAREDE CHINA", localizacao: "Changzhou, Jiangsu, China", provincia: "Jiangsu", fobUsd: 393882, percentualMercado: 5.37, pesoKg: 189621, relevancia: "top", especialidade: "Pet Training Pads, Puppy Pads, Dog Pee Pads", marcas: ["CAREDE"], site: "https://www.czcarede.com", areaM2: 20000, linhasProducao: 26, certificacoes: ["ISO", "CE"], tamanhos: ["56x56cm", "56x58cm", "40x60cm", "60x60cm", "60x90cm", "76x90cm"], descricao: "Fabrica com 20.000 m2 e 26 linhas de producao. Exporta para Europa, EUA, Oriente Medio e Asia." },
  { id: 4, nome: "Xiamen Yanjan Daily Necessities Co., Ltd.", nomeLogcomex: "XIAMEN YANJAN CHINA", localizacao: "Xiamen, Fujian, China", provincia: "Fujian", fobUsd: 361435, percentualMercado: 4.93, pesoKg: 235071, relevancia: "top", especialidade: "Pet Pads, Puppy Training Pads, Bamboo Fiber Pads", marcas: ["YANJAN"], site: "https://www.yanjan.com", certificacoes: ["ISO 9001", "CE", "SGS"], descricao: "Localizado em Xiamen (Fujian), um dos principais polos de exportacao da China." },
  { id: 5, nome: "ElinTree (Xiamen) Life Products Technology Co., Ltd.", nomeLogcomex: "-", localizacao: "Xiamen, Fujian, China", provincia: "Fujian", relevancia: "alto", especialidade: "Pet Pads, Baby Diapers, Adult Care, Underpads, Wet Wipes", marcas: ["ELINTREE"], site: "https://www.elintree.com", contato: "sales@elintree.com | +86 15359273309", linhasProducao: 15, capacidadeMensal: "50 milhoes/mes", capacidadeAnual: "800 milhoes/ano", moq: "100.000 pecas (private label)", certificacoes: ["CE", "FDA", "ISO 9001", "ISO 13485", "OEKO-TEX", "FSC"], descricao: "15 linhas de producao, capacidade de 800 milhoes de tapetes por ano. Aceita private label a partir de 100.000 pecas." },
  { id: 6, nome: "Xiamen Newclears Daily Products Co., Ltd.", nomeLogcomex: "-", localizacao: "Jimei District, Xiamen, Fujian, China", provincia: "Fujian", relevancia: "alto", especialidade: "Pet Pads, Baby Diapers, Adult Diapers, Wet Wipes, Bamboo Fiber Series", marcas: ["NEWCLEARS"], site: "https://www.newclears.com", contato: "sales@newclears.com | +86 1735 0035 603", fundacao: 2009, areaM2: 50000, linhasProducao: 18, certificacoes: ["ISO", "CE", "SGS"], descricao: "Fundada em 2009, area de 50.000 m2 com 18 linhas de producao (3 dedicadas a tapetes para pets)." },
  { id: 7, nome: "Hangzhou Jeenor Pet Products Co., Ltd.", nomeLogcomex: "HANGZHOU JEENOR CHINA", localizacao: "Hangzhou, Zhejiang, China", provincia: "Zhejiang", relevancia: "alto", especialidade: "Pet Training Pads, Puppy Pads, Dog Diapers", marcas: ["JEENOR"], site: "https://www.jeenor.com", certificacoes: ["ISO", "CE"], descricao: "Fabricante de Hangzhou especializado em produtos para treinamento de pets." },
  { id: 8, nome: "Zhejiang Wipex Hygiene Products Co., Ltd.", nomeLogcomex: "ZHEJIANG WIPEX CHINA", localizacao: "Zhejiang, China", provincia: "Zhejiang", relevancia: "alto", especialidade: "Pet Pads, Wet Wipes, Non-Woven Products", marcas: ["WIPEX"], certificacoes: ["ISO 9001", "CE"], descricao: "Fabricante de Zhejiang com foco em produtos de nao-tecido para higiene pet e domestica." },
  { id: 9, nome: "Qingdao D&R Hygienic Products Co., Ltd.", nomeLogcomex: "QINGDAO DR CHINA", localizacao: "Qingdao, Shandong, China", provincia: "Shandong", relevancia: "medio", especialidade: "Puppy Pads, Dog Diapers, Washable Pads, Poo Bag, Pet Wipes", marcas: ["D&R"], site: "https://dnrpad.en.alibaba.com", precoUsd: "US$ 0,02-0,17 / peca", moq: "500 pecas", certificacoes: ["ISO", "CE"], descricao: "Fabricante de Qingdao com precos competitivos. MOQ de apenas 500 pecas." },
  { id: 10, nome: "Jiangsu Dezhu Sanitary Products Co., Ltd.", nomeLogcomex: "JIANGSU DEZHU CHINA", localizacao: "Jiangsu, China", provincia: "Jiangsu", relevancia: "medio", especialidade: "Dog Pet Training Pads, Bamboo Charcoal Pet Training Pads, Puppy Pads", marcas: ["DEZHU"], site: "https://dzwsyp.en.alibaba.com", precoUsd: "US$ 0,03-0,09 / peca", moq: "1.000 pecas", certificacoes: ["ISO9001:2015"], descricao: "Diamond Member no Alibaba. Especializado em tapetes com carvao de bambu." },
  { id: 11, nome: "Shenzhen Rockbrook Daily Products Co., Limited", nomeLogcomex: "-", localizacao: "Shenzhen, Guangdong, China", provincia: "Guangdong", relevancia: "medio", especialidade: "Bamboo Charcoal Pet Pads, Non-Woven Pet Training Pads, OEM Private Label", marcas: ["ROCKBROOK"], site: "https://rockbrook.en.alibaba.com", receitaUsd: "US$ 10M - 50M", anosAlibaba: 11, tradeAssuranceUsd: 804000, taxaResposta: "91,2%", certificacoes: ["Trade Assurance"], descricao: "11 anos no Alibaba, receita de US$ 10-50M. Especializado em tapetes de carvao de bambu e OEM." },
  { id: 12, nome: "Shaoxing Shangyu Jiani Household Products Co., Ltd.", nomeLogcomex: "-", localizacao: "Shaoxing, Zhejiang, China", provincia: "Zhejiang", relevancia: "medio", especialidade: "Disposable Extra Large Washable Pee Puppy Pet Dog Cat Toilet Training Pads", marcas: ["JIANICAT"], site: "https://jiani.en.alibaba.com", receitaUsd: "US$ 5M - 10M", taxaResposta: "96,1%", descricao: "Receita de US$ 5-10M. 30% das exportacoes vao para America do Norte." },
  { id: 13, nome: "Tex-Cel Shanghai Co., Ltd.", nomeLogcomex: "-", localizacao: "Shanghai, China", provincia: "Shanghai", relevancia: "medio", especialidade: "Waterproof Reusable Washable Puppy Dog Pee Pads", marcas: ["TEX-CEL"], site: "https://texcel.en.alibaba.com", receitaUsd: "US$ 5M - 10M", taxaResposta: "72,1%", certificacoes: ["SGS"], descricao: "60% das exportacoes para America do Norte. Especializado em tapetes lavaveis e reutilizaveis." },
  { id: 14, nome: "Hangzhou Brilliant Hygiene Products Co., Ltd.", nomeLogcomex: "HANGZHOU BRILLIANT CHINA", localizacao: "Hangzhou, Zhejiang, China", provincia: "Zhejiang", relevancia: "alto", especialidade: "Pet Pads, Baby Diapers, Wet Wipes", marcas: ["BRILLIANT"], descricao: "Fabricante de Hangzhou com linha completa de produtos higienicos." },
  { id: 15, nome: "Tianjin Wholesome Hygiene Products Co., Ltd.", nomeLogcomex: "TIANJIN WHOLESOME CHINA", localizacao: "Tianjin, China", provincia: "Tianjin", relevancia: "medio", especialidade: "Pet Pads, Hygiene Products", marcas: ["WHOLESOME"], descricao: "Fabricante de Tianjin, mesmo polo industrial de Tianjin Yiyi." },
  { id: 16, nome: "Henan Delight Hygiene Products Co., Ltd.", nomeLogcomex: "HENAN DELIGHT CHINA", localizacao: "Henan, China", provincia: "Henan", relevancia: "medio", especialidade: "Pet Training Pads, Dog Pee Pads, Puppy Pads", marcas: ["DELIGHT"], descricao: "Fabricante da provincia de Henan com foco em tapetes de treinamento para pets." },
  { id: 17, nome: "Deyi Hygiene Products Co., Ltd.", nomeLogcomex: "DEYI HYGIENE CHINA", localizacao: "China", provincia: "Nao identificada", relevancia: "medio", especialidade: "Hygiene Products, Pet Pads", marcas: ["DEYI HYGIENE"], descricao: "Fabricante identificado na LogComex com marca propria DEYI HYGIENE." },
  { id: 18, nome: "Linyi Highland International Trade Co., Ltd.", nomeLogcomex: "LINYI HIGHLAND CHINA", localizacao: "Linyi, Shandong, China", provincia: "Shandong", relevancia: "medio", especialidade: "Pet Diapers, Pet Training Pad, Pet Supplies, Adult Diapers", marcas: ["HIGHLAND"], site: "https://highlandly.en.alibaba.com", descricao: "Trading de Linyi (Shandong) com ampla linha de produtos higienicos para pets e adultos." },
  { id: 19, nome: "Changzhou AM Hygiene Products Co., Ltd.", nomeLogcomex: "CHANGZHOU AM CHINA", localizacao: "Changzhou, Jiangsu, China", provincia: "Jiangsu", relevancia: "alto", especialidade: "Pet Training Pads, Dog Diapers, Puppy Pads", marcas: ["AM"], descricao: "Fabricante de Changzhou (Jiangsu), mesmo polo de Care-De." },
  { id: 20, nome: "Yiwu Sunmile Trading Co., Ltd.", nomeLogcomex: "YIWU SUNMILE CHINA", localizacao: "Yiwu, Zhejiang, China", provincia: "Zhejiang", relevancia: "alto", especialidade: "Pet Pads, Pet Supplies, Hygiene Products", marcas: ["SUNMILE"], descricao: "Trading de Yiwu (maior centro de comercio atacadista do mundo) com foco em produtos para pets." },
];

export const materiais = [
  { nome: "Polpa de Celulose (Fluff Pulp)", funcao: "Nucleo absorvente", descricao: "Principal material absorvente. Derivado de madeira de pinheiro ou eucalipto. Pode ser combinado com SAP para maior absorcao.", origemPrincipal: "Brasil, EUA, Chile, Canada", custoRelativo: "Medio", cor: "bg-amber-100 border-amber-300" },
  { nome: "SAP - Polimero Superabsorvente", funcao: "Absorcao e retencao de liquidos", descricao: "Granulos de poliacrilato de sodio que absorvem ate 300x seu peso em liquido. Transforma urina em gel solido.", origemPrincipal: "China, Japao, Alemanha", custoRelativo: "Alto", cor: "bg-blue-100 border-blue-300" },
  { nome: "Non-Woven de Polipropileno (PP Spunbond)", funcao: "Camada superior (contato com o pet)", descricao: "Falso tecido permeavel que permite a passagem do liquido para o nucleo. Macio ao toque, nao irrita a pele.", origemPrincipal: "China, India", custoRelativo: "Baixo", cor: "bg-green-100 border-green-300" },
  { nome: "Filme de Polietileno (PE Film)", funcao: "Camada inferior (barreira impermeavel)", descricao: "Filme plastico impermeavel que impede vazamentos. Pode ser texturizado para evitar deslizamento.", origemPrincipal: "China, Arabia Saudita", custoRelativo: "Baixo", cor: "bg-gray-100 border-gray-300" },
  { nome: "Fibra de Bambu", funcao: "Camada superior alternativa (premium)", descricao: "Alternativa ecologica ao non-woven de PP. Propriedades antibacterianas naturais. Mais macia e biodegradavel.", origemPrincipal: "China", custoRelativo: "Alto", cor: "bg-emerald-100 border-emerald-300" },
  { nome: "Carvao de Bambu (Bamboo Charcoal)", funcao: "Controle de odores", descricao: "Adicionado ao nucleo absorvente para neutralizar odores. Produto premium com apelo ecologico.", origemPrincipal: "China", custoRelativo: "Alto", cor: "bg-zinc-100 border-zinc-300" },
  { nome: "Polipropileno Tecido (Woven PP)", funcao: "Base antiderrapante (lavaveis)", descricao: "Usado em tapetes lavaveis como base resistente. Suporta multiplas lavagens.", origemPrincipal: "China, India", custoRelativo: "Medio", cor: "bg-orange-100 border-orange-300" },
  { nome: "Gel de Silica", funcao: "Absorcao e controle de odores (alternativo)", descricao: "Usado em tapetes premium como alternativa ao SAP. Excelente controle de odores.", origemPrincipal: "China", custoRelativo: "Alto", cor: "bg-purple-100 border-purple-300" },
];

export const tiposProduto = [
  { tipo: "Standard Descartavel", descricao: "Tapete basico descartavel com nucleo de celulose e SAP. Camada superior de non-woven PP, inferior de PE.", tamanhos: ["33x45cm", "45x60cm", "60x60cm", "60x90cm"], camadas: 5, absorcaoMl: "400-600 ml", precoFobUsd: "US$ 0,02-0,05 / peca", uso: "Uso diario, treinamento basico", publico: "Todos os portes de caes", badge: "Mais vendido", badgeColor: "bg-blue-600" },
  { tipo: "Premium com SAP Reforcado", descricao: "Tapete com maior concentracao de SAP, 6 camadas, bordas seladas e indicador de umidade.", tamanhos: ["45x60cm", "60x60cm", "60x90cm", "76x90cm"], camadas: 6, absorcaoMl: "800-1.200 ml", precoFobUsd: "US$ 0,05-0,12 / peca", uso: "Uso intensivo, caes de medio e grande porte", publico: "Caes adultos, racas grandes", badge: "Premium", badgeColor: "bg-amber-600" },
  { tipo: "Bambu / Ecologico", descricao: "Camada superior de fibra de bambu com propriedades antibacterianas. Mais ecologico e biodegradavel.", tamanhos: ["45x60cm", "60x60cm", "60x90cm"], camadas: 5, absorcaoMl: "500-800 ml", precoFobUsd: "US$ 0,06-0,15 / peca", uso: "Consumidores ecologicamente conscientes", publico: "Todos os portes", badge: "Eco", badgeColor: "bg-green-600" },
  { tipo: "Carvao de Bambu (Anti-odor)", descricao: "Nucleo com particulas de carvao de bambu para neutralizacao de odores. Produto premium.", tamanhos: ["45x60cm", "60x60cm", "60x90cm"], camadas: 6, absorcaoMl: "600-900 ml", precoFobUsd: "US$ 0,07-0,18 / peca", uso: "Ambientes fechados, apartamentos", publico: "Caes de pequeno e medio porte", badge: "Anti-odor", badgeColor: "bg-zinc-700" },
  { tipo: "Lavavel / Reutilizavel", descricao: "Tapete de tecido com camada absorvente interna e base impermeavel. Suporta 300+ lavagens.", tamanhos: ["40x50cm", "50x70cm", "60x90cm", "80x100cm"], camadas: 3, absorcaoMl: "300-500 ml", precoFobUsd: "US$ 1,50-8,00 / peca", uso: "Uso sustentavel, longo prazo", publico: "Todos os portes", badge: "Reutilizavel", badgeColor: "bg-teal-600" },
  { tipo: "Jumbo / XL", descricao: "Tapete de grande formato para caes de grande porte ou multiplos caes.", tamanhos: ["76x90cm", "90x120cm", "100x150cm"], camadas: 6, absorcaoMl: "1.500-2.500 ml", precoFobUsd: "US$ 0,15-0,35 / peca", uso: "Caes grandes, multiplos animais", publico: "Racas grandes (Labrador, Pastor Alemao, etc.)", badge: "Jumbo", badgeColor: "bg-red-600" },
  { tipo: "Treinamento com Atrativo", descricao: "Tapete com feromonios ou atrativos olfativos para facilitar o treinamento de filhotes.", tamanhos: ["45x60cm", "60x60cm"], camadas: 5, absorcaoMl: "400-600 ml", precoFobUsd: "US$ 0,04-0,10 / peca", uso: "Treinamento de filhotes", publico: "Filhotes de todas as racas", badge: "Treinamento", badgeColor: "bg-violet-600" },
  { tipo: "Hospitalar / Veterinario", descricao: "Tapete de uso veterinario com alta absorcao e propriedades antibacterianas. Embalagem individual.", tamanhos: ["60x60cm", "60x90cm", "90x120cm"], camadas: 6, absorcaoMl: "1.000-2.000 ml", precoFobUsd: "US$ 0,10-0,30 / peca", uso: "Clinicas veterinarias, pos-cirurgico", publico: "Uso profissional", badge: "Veterinario", badgeColor: "bg-sky-600" },
];

export const tutorialEtapas = [
  { etapa: 1, titulo: "Habilitacao no SISCOMEX", descricao: "Cadastre sua empresa no SISCOMEX (Sistema Integrado de Comercio Exterior) atraves do Portal Unico do Comercio Exterior (PUCOMEX). Necessario CNPJ ativo, Inscricao Estadual e Contrato Social.", orgao: "Receita Federal / MDIC", prazo: "5-15 dias uteis", documentos: ["CNPJ ativo", "Inscricao Estadual", "Contrato Social", "Procuracao para Despachante (opcional)"], dica: "Empresas com faturamento acima de R$ 150.000/ano devem se habilitar como Importador Habitual." },
  { etapa: 2, titulo: "Verificacao MAPA e ANVISA", descricao: "Tapetes higienicos para pets NAO precisam de registro na ANVISA. Verificar com o MAPA se ha necessidade de licenca para importacao - geralmente nao e necessaria para tapetes sinteticos.", orgao: "MAPA / ANVISA", prazo: "Consulta previa: 1-3 dias", documentos: ["Consulta previa ao MAPA", "Verificacao de licenca nao-automatica no SISCOMEX"], dica: "NCM 4818.90.90 nao esta sujeito a licenciamento nao automatico na maioria dos casos." },
  { etapa: 3, titulo: "Selecao e Qualificacao do Fornecedor", descricao: "Pesquise fornecedores no Alibaba, Made-in-China ou via LogComex. Solicite amostras, verifique certificacoes (ISO, CE, SGS) e faca auditoria da fabrica (presencial ou via terceiros).", orgao: "Alibaba / Made-in-China / LogComex", prazo: "2-8 semanas", documentos: ["Solicitacao de amostras", "Certificacoes ISO/CE/SGS", "Relatorio de auditoria SGS ou BV"], dica: "Use a LogComex para identificar quais fabricas ja exportam para o Brasil - isso reduz muito o risco." },
  { etapa: 4, titulo: "Negociacao e Contrato", descricao: "Negocie preco FOB, Incoterm, prazo de entrega, condicoes de pagamento (T/T, L/C) e especificacoes tecnicas. Formalize em Purchase Order (PO) ou Sales Contract.", orgao: "Fornecedor Chines", prazo: "1-2 semanas", documentos: ["Purchase Order (PO)", "Sales Contract", "Proforma Invoice"], dica: "Prefira Incoterm FOB para ter controle sobre o frete. Pagamento: 30% adiantado + 70% contra BL." },
  { etapa: 5, titulo: "Contratacao de Frete e Seguro", descricao: "Contrate um freight forwarder para frete maritimo (FCL ou LCL). Principais portos de embarque: Tianjin, Qingdao, Shanghai, Ningbo, Xiamen. Destino: Santos (SP), Itajai (SC), Paranagua (PR).", orgao: "Freight Forwarder", prazo: "Contratacao: 1-3 dias | Transito: 25-35 dias", documentos: ["Booking Confirmation", "Apolice de Seguro", "Instrucao de Embarque"], dica: "Itajai (SC) e o porto mais utilizado para esse produto - menor custo de armazenagem e desembaraco." },
  { etapa: 6, titulo: "Documentacao de Exportacao", descricao: "Solicite ao fornecedor: Commercial Invoice, Packing List, Bill of Lading (BL), Certificate of Origin (CO), e laudos de qualidade se necessario.", orgao: "Fornecedor Chines", prazo: "Apos embarque: 3-7 dias", documentos: ["Commercial Invoice", "Packing List", "Bill of Lading (BL)", "Certificate of Origin (CO) - Form A para SGP", "Laudo de Qualidade SGS/BV (opcional)", "MSDS (Material Safety Data Sheet)"], dica: "O Certificate of Origin Form A permite reducao do II via SGP (Sistema Geral de Preferencias)." },
  { etapa: 7, titulo: "Registro da DI e Desembaraco Aduaneiro", descricao: "Apos chegada da carga, registre a Declaracao de Importacao (DI) no SISCOMEX. O despachante realiza o desembaraco. A carga pode ser parametrizada em canal verde, amarelo, vermelho ou cinza.", orgao: "Receita Federal / Despachante Aduaneiro", prazo: "Canal Verde: 1 dia | Amarelo: 2-5 dias | Vermelho: 5-15 dias", documentos: ["Declaracao de Importacao (DI)", "Comprovante de Pagamento dos Tributos", "Nota Fiscal de Entrada"], dica: "Tributos NCM 4818.90.90: II 14,4% + IPI 3,25% + PIS 2,1% + COFINS 9,65% + ICMS (varia por estado)." },
  { etapa: 8, titulo: "Registro de Marca e Embalagem", descricao: "Registre sua marca no INPI para proteger sua identidade comercial. Adeque a embalagem as normas brasileiras: idioma portugues, CNPJ do importador, pais de origem, composicao do produto.", orgao: "INPI", prazo: "Registro de marca: 12-18 meses", documentos: ["Pedido de Registro de Marca no INPI", "Embalagem em portugues", "CNPJ do importador na embalagem", "Indicacao: MADE IN CHINA", "Composicao dos materiais"], dica: "Solicite o registro de marca ANTES de lancar o produto no mercado para garantir exclusividade." },
];

export const aliquotas = {
  ncm: "4818.90.90",
  descricao: "Outros artigos de papel, para uso sanitario/domestico/hospitalar",
  tributos: [
    { nome: "II - Imposto de Importacao", aliquota: "14,4%", base: "Valor CIF", cor: "bg-red-100 text-red-800 border-red-200" },
    { nome: "IPI - Imposto sobre Produtos Industrializados", aliquota: "3,25%", base: "CIF + II", cor: "bg-orange-100 text-orange-800 border-orange-200" },
    { nome: "PIS", aliquota: "2,1%", base: "CIF + II + IPI", cor: "bg-yellow-100 text-yellow-800 border-yellow-200" },
    { nome: "COFINS", aliquota: "9,65%", base: "CIF + II + IPI", cor: "bg-amber-100 text-amber-800 border-amber-200" },
    { nome: "ICMS - Sao Paulo", aliquota: "18%", base: "Base ICMS", cor: "bg-blue-100 text-blue-800 border-blue-200" },
    { nome: "ICMS - Santa Catarina", aliquota: "17%", base: "Base ICMS", cor: "bg-indigo-100 text-indigo-800 border-indigo-200" },
  ],
  observacoes: [
    "Aliquota do II pode ser reduzida via Ex-Tarifario ou acordos comerciais",
    "Certificate of Origin Form A (SGP) pode reduzir o II",
    "Tapetes higienicos para pets NAO precisam de registro na ANVISA",
    "Drawback: possivel para empresas que reexportam produtos transformados",
    "Simples Nacional: tratamento diferenciado de tributos",
  ],
};
