// Dados de contato dos importadores brasileiros de tapetes higiênicos para pets
// Fonte: LogComex NCM 4818.90.90 + pesquisa Receita Federal / Google / LinkedIn
// Período: Jun/2025–Mai/2026

export interface ImportadorContato {
  nome: string;
  cnpj: string;
  cidade: string;
  estado: string;
  endereco: string;
  telefone: string;
  email: string;
  site: string;
  instagram: string;
  segmento: string;
  observacao: string;
  fobUsd: number;
  percentual: number;
  pesoKg: number;
}

export const importadoresContato: ImportadorContato[] = [
  {
    nome: "BM3 IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "12.098.843/0001-51",
    cidade: "Aruja",
    estado: "SP",
    endereco: "Edifício Absolute Business, Rua Dr. Pedro Ferreira, 333, 6º andar, Centro, Itajaí, SC - 88301-030",
    telefone: "(48) 3513-1500",
    email: "eric@bm3.com",
    site: "https://bm3.com.br/",
    instagram: "@bm3trading",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 2638553.0,
    percentual: 35.99,
    pesoKg: 870294.0,
  },
  {
    nome: "LALA PET IMPORT LTDA",
    cnpj: "54.347.030/0001-06",
    cidade: "Maceio",
    estado: "AL",
    endereco: "Rua Carijos, 107 - Vila Alzira, Santo André - SP, 09180-000",
    telefone: "(11) 8656-5362 ou (11) 4455-0027",
    email: "contato@moderncont.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Empresa fundada em 15/03/2024 e com situação cadastral ATIVA.",
    fobUsd: 559204.0,
    percentual: 7.63,
    pesoKg: 331412.0,
  },
  {
    nome: "PETGLOBAL IMPORTACAO E COMERCIO DE PRODUTOS PARA ANIMAIS LTDA",
    cnpj: "62.609.336/0001-03",
    cidade: "Imbituba",
    estado: "SC",
    endereco: "R ANTONIO JOSE PEREZ CORREA 1322 C A, Loteamento Jardim B, Maringa - PR",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A empresa está registrada como Comércio varejista de artigos do vestuário e acessórios. Não foi possível confirmar a importação de tapetes higiênicos para pets.",
    fobUsd: 427522.0,
    percentual: 5.83,
    pesoKg: 205308.0,
  },
  {
    nome: "UNIPET DISTRIBUIDORA DE PRODUTOS AGROPECUARIOS LTDA",
    cnpj: "07.650.604/0001-22",
    cidade: "Itajai",
    estado: "SC",
    endereco: "Rua Erich Froehner, 1.031, Schroeder - SC",
    telefone: "(47) 3374-5723",
    email: "pet@unipetdistribuidora.com.br",
    site: "Não encontrado",
    instagram: "@unipetdistribuidora",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 298139.0,
    percentual: 4.07,
    pesoKg: 175560.0,
  },
  {
    nome: "HIGIEFARM - COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "00.881.434/0001-48",
    cidade: "Itajai",
    estado: "SC",
    endereco: "Av. João Elustondo Filho, 260, Sarandi, Porto Alegre - RS",
    telefone: "(51) 3364-7589",
    email: "gerencia@higiefarm.com.br",
    site: "https://higiefarm.com.br/",
    instagram: "https://www.instagram.com/higiefarm/",
    segmento: "Pet",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 277050.0,
    percentual: 3.78,
    pesoKg: 177427.0,
  },
  {
    nome: "INOVEN INDUSTRIA, COMERCIO E IMPORTACAO LTDA",
    cnpj: "07.826.504/0002-95",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Rua João Thomaz Pinto, 1570 – Galpão E – Módulos 1, 2 e 3 – Cond. Byblos, Canhanduba – Itajaí - SC",
    telefone: "(47) 4141-0017",
    email: "Não encontrado",
    site: "https://inoven.com.br/",
    instagram: "https://www.instagram.com/inoven.brasil/",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MEC G STORE IMPORTS LTDA",
    cnpj: "29.050.381/0001-03",
    cidade: "Santo André",
    estado: "SP",
    endereco: "Avenida dos Estados, 1345 - Santa Terezinha, Santo Andre - SP, 09.210-580",
    telefone: "(11) 4451-9138",
    email: "contato@mecg.com.br",
    site: "https://www.mecg.com.br",
    instagram: "https://www.instagram.com/mecgstore/",
    segmento: "Pet",
    observacao: "A empresa atua no comércio varejista, oferecendo itens para o lar, lazer e utilidades domésticas, incluindo artigos para pets. Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "M HAMEED COMERCIO DE PRODUTOS DE BELEZA E BARBEARIA - ME",
    cnpj: "27.679.172/0004-32",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Líbero Badaró, 306, Andar 6 Sala 02, Centro, São Paulo - SP",
    telefone: "(11) 98906-6226",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "https://www.instagram.com/ranacosmeticos786/",
    segmento: "Trading/Importadora",
    observacao: "A empresa atua como fabricante, importadora e exportadora de cosméticos e acessórios para barbearia e salão. Não foi encontrada confirmação explícita sobre a importação de tapetes higiênicos para pets, mas há registros de importação de outros produtos.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TEQLA COMERCIO E SUPRIMENTOS LTDA",
    cnpj: "55.964.470/0001-67",
    cidade: "Pato Branco",
    estado: "PR",
    endereco: "Rua Maria Lora, 251, Menino Deus, Pato Branco - PR",
    telefone: "(46) 99110-1419",
    email: "sac@teqla.com.br",
    site: "https://www.teqla.com.br",
    instagram: "https://instagram.com/teqla_br",
    segmento: "Pet",
    observacao: "A Teqla é uma empresa dedicada à produção, importação e distribuição de soluções descartáveis. O site menciona produtos como protetores de colchão e lenços de banho, e o CNAE secundário inclui comércio varejista de artigos para animais de estimação.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "HOSPFLEX EMBALAGENS LTDA",
    cnpj: "03.431.790/0001-58",
    cidade: "Sorocaba",
    estado: "SP",
    endereco: "Av. Com. Camilo Júlio n°2655 U.A.C.7 Jd. Ibiti do Paço, Sorocaba - SP",
    telefone: "(15) 3211-6128",
    email: "central.hospflex@gmail.com",
    site: "https://www.hospflex.com.br/",
    instagram: "@hospflex",
    segmento: "Higiene Hospitalar",
    observacao: "Não importa tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ESSITY DO BRASIL INDUSTRIA E COMERCIO LTDA",
    cnpj: "72.899.016/0001-99",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Dr Rubens Gomes Bueno, 691, Andar 19 Conj 192 a 196 - Varzea de Baixo, São Paulo - SP",
    telefone: "(11) 3602-7700",
    email: "ALEXANDRE.BERNARDES@ESSITY.COM",
    site: "https://www.essity.com/",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A empresa é líder global em higiene e saúde, importando produtos como tapetes higiênicos para pets (NCM 4818.90.90). Possui perfil global no Instagram (@essity) e uma página de localização para 'Essity do Brasil' com telefone.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MULTI-MARCAS INDUSTRIA DE PRODUTOS HIGIENICOS LTDA",
    cnpj: "31.277.525/0001-00",
    cidade: "Terezópolis de Goiás",
    estado: "GO",
    endereco: "Rod. Terezópolis a Nerópolis, KM 2, Terezópolis de Goiás - GO - 75175-000",
    telefone: "(62) 2020-5656",
    email: "contato@multimarcasindustria.com.br",
    site: "https://multimarcasindustria.com/",
    instagram: "https://www.instagram.com/multimarcas.industria/",
    segmento: "Outro",
    observacao: "Empresa atua no segmento de higiene pessoal, incluindo fraldas infantis e adultas. Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "NORDSTROM COMERCIAL LTDA",
    cnpj: "46.895.059/0001-96",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Rua Brusque, 579, Centro, Itajaí - SC, 88.302-001",
    telefone: "(47) 99257-2197",
    email: "contato@nordstromtrade.com.br",
    site: "https://nordstromtrade.com.br",
    instagram: "@nordstromtrade",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "BOMA COMERCIO LTDA",
    cnpj: "05.167.642/0001-01",
    cidade: "MAGE",
    estado: "RJ",
    endereco: "R WALDEMAR COLOMBO GARCIA 491 PARTE, Andorinhas, Mage - RJ",
    telefone: "(21) 2630-2563",
    email: "sac@bomdental.com.br",
    site: "https://bomadental.com.br/",
    instagram: "@boma.odontologia",
    segmento: "Outro",
    observacao: "A empresa atua no segmento de produtos odontológicos e não há indícios de importação de tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "FELIPE SIELSKI ROMUALDO DE OLIVEIRA COMERCIO VAREJISTA",
    cnpj: "55.408.730/0001-18",
    cidade: "Curitiba",
    estado: "PR",
    endereco: "AV FLORIAN POLIS 1319, Cajuru, Curitiba - PR, 82930-030",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Telefone mascarado em sites de consulta pública.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MELO PET SHOP - COMERCIO DE RACOES LTDA",
    cnpj: "09.439.591/0001-72",
    cidade: "Curitiba",
    estado: "PR",
    endereco: "Rua Engenheiros Rebouças, 1826, Rebouças, Curitiba - PR",
    telefone: "(41) 3333-7226",
    email: "contato@casadoprodutor.com.br",
    site: "https://www.casadoprodutor.com.br",
    instagram: "https://www.instagram.com/melopetshop_/",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CONNECTA IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "04.581.264/0001-37",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Avenida Coronel Marcos Konder, 1024, Sala 33, Centro, Itajaí - SC",
    telefone: "(47) 3048-0087",
    email: "aline@connectatrading.com.br",
    site: "https://connectatrading.com.br",
    instagram: "@connectatrading",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "SUDAMERICA TRADING LTDA",
    cnpj: "44.405.291/0001-73",
    cidade: "Porto Velho",
    estado: "RO",
    endereco: "Avenida Pinheiro Machado, 753, Edif Nilos Sala 04, Olaria, Porto Velho - RO, 76801-235",
    telefone: "(13) 99911-7297",
    email: "lperazzo@loglinelogistica.com.br",
    site: "https://sudamericatrading.com.br/",
    instagram: "Não encontrado (associado a Logline Logística: @loglinelogistica)",
    segmento: "Trading/Importadora",
    observacao: "Site oficial em construção. E-mail e telefone associados à Logline Logística.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "AGORA 2 GO IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "53.577.386/0001-65",
    cidade: "RIO DE JANEIRO",
    estado: "RJ",
    endereco: "RUA SANDRO MOREIRA, 00101, RECREIO DOS BANDEIRANTES, RIO DE JANEIRO - RJ",
    telefone: "(21) 3617-4776",
    email: "LEGALIZACAO@QRCONTABILIDADE.COM.BR",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "COMERCIAL BRASIL ATACADISTA DE PRODUTOS ALIMENTICIOS LTDA",
    cnpj: "15.379.804/0001-10",
    cidade: "Guarulhos",
    estado: "SP",
    endereco: "AV AMANCIO GAIOLLI 1717 EDIF 1, Agua Chata, Guarulhos - SP",
    telefone: "(11) 2413-7215",
    email: "fiscal@nagumo.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "THCR COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "13.074.140/0001-56",
    cidade: "Guarulhos",
    estado: "SP",
    endereco: "Rua Monte Aprazivel, 155, Galpao01, Jardim Santo Afonso, Guarulhos - SP",
    telefone: "(11) 4646-4989",
    email: "escritorio@cdcontabil.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "SUPERIA TRADING LTDA",
    cnpj: "05.898.253/0001-48",
    cidade: "Vitória",
    estado: "ES",
    endereco: "Rua Clóvis Machado, 176, Sala 410, Enseada do Sua, Vitória - ES, 29.050-900",
    telefone: "(47) 2125-1605",
    email: "relacionamento@superia.global",
    site: "https://www.superia.global/",
    instagram: "https://www.instagram.com/superia.global/?hl=pt",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MUNDORA IMPORTACAO E DISTRIBUICAO LTDA",
    cnpj: "38.477.249/0001-65",
    cidade: "Penha",
    estado: "SC",
    endereco: "Rua Brasilia, 370, Sala 01, Centro, Penha - SC",
    telefone: "(47) 3345-8184",
    email: "ecommerce@etilux.com.br",
    site: "https://www.etilux.com.br",
    instagram: "https://www.instagram.com/mundora_imports/",
    segmento: "Trading/Importadora",
    observacao: "O e-mail e telefone encontrados são do Grupo Etilux, que parece ser relacionado à Mundora Importação e Distribuição LTDA, conforme informações da Tendata e e-mails de contato de funcionários da Mundora.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "STERILEX CIENTIFICA LTDA",
    cnpj: "03.541.994/0001-41",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Dr. João Batista de Lacerda, 168, Quarta Parada, São Paulo - SP",
    telefone: "(11) 2606-5349",
    email: "sterilex@sterilex.com.br",
    site: "https://sterilex.com.br/",
    instagram: "https://www.instagram.com/sterilexcientifica/",
    segmento: "Higiene Hospitalar",
    observacao: "Não há indícios de que a empresa importe tapetes higiênicos para pets. O foco principal é em produtos para uso médico, cirúrgico, hospitalar e de laboratórios.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "RICA COMERCIO E SERVICOS LTDA",
    cnpj: "12.152.796/0001-87",
    cidade: "COLOMBO",
    estado: "PR",
    endereco: "AV MARGINAL DIREITA 704 B, SANTA TEREZINHA, COLOMBO - PR",
    telefone: "(11) 2946-0846",
    email: "cassia@wbtc.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A atividade principal da empresa é Suporte técnico, manutenção e outros serviços em tecnologia da informação. Não foi encontrada evidência clara de importação de tapetes higiênicos para pets (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "GARRA ANIMAL COMERCIO ATACADISTA DE MEDICAMENTOS E DROGAS DE USO VETERINARIO LTDA",
    cnpj: "21.445.041/0001-61",
    cidade: "Campina Grande",
    estado: "PB",
    endereco: "Rua Quinze de Novembro, 1120, Jardim Continental, Campina Grande - PB",
    telefone: "(83) 3142-1312",
    email: "ecommerce@garraanimal.com.br",
    site: "https://www.garraanimal.com.br/",
    instagram: "https://www.instagram.com/grupogarraanimal/",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MJK IMPORTACAO EXPORTACAO E REPRESENTACAO LTDA",
    cnpj: "08.486.685/0001-30",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Av. Brigadeiro Faria Lima, 3015 Conj. 92 - Jd. Paulistano, São Paulo - SP, 01452-000",
    telefone: "(11) 3707-9820",
    email: "contato@mjkie.com",
    site: "https://mjkie.com/",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DAISO BRASIL COMERCIO E IMPORTACAO LTDA",
    cnpj: "14.987.685/0001-16",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Avenida Paulista, 37, Conj 11 e 12, Bela Vista, São Paulo - SP",
    telefone: "Não encontrado",
    email: "vendasonline@daisobrasil.com.br",
    site: "https://www.daiso.com.br",
    instagram: "@daisojapanbrasil",
    segmento: "Varejo",
    observacao: "A empresa possui diversas filiais com CNPJs diferentes. O CNPJ principal (matriz) é 14.987.685/0001-16. O e-mail e endereço de contato são do e-commerce.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "SENIOR COMERCIAL, IMPORTACAO E DISTRIBUICAO LTDA",
    cnpj: "41.707.896/0001-20",
    cidade: "ITAJAI",
    estado: "SC",
    endereco: "Rua Dr. Nereu Ramos, 197, Edifício Seixas, Sala 1002, Centro, Itajaí - SC",
    telefone: "(47) 3224-0692",
    email: "contato@seniortrade.com.br",
    site: "https://seniortrade.com.br/",
    instagram: "https://www.instagram.com/seniortradebr/",
    segmento: "Trading/Importadora",
    observacao: "Empresa especializada em supply chain management, importação e exportação.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "PRIME OFFICE LTDA",
    cnpj: "52.085.759/0001-18",
    cidade: "Maravilha",
    estado: "SC",
    endereco: "Avenida Orlando Valério Zawadzki, 250 - Bairro Universitário, Maravilha - SC",
    telefone: "(49) 98838-3343",
    email: "atendimento@primeoffice.ind.br",
    site: "https://www.lojaprimeoffice.com.br",
    instagram: "https://www.instagram.com/primeoffice.ind",
    segmento: "Outro",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil. Atua na venda de móveis e utilidades para o lar.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ALWAYS COMERCIAL IMPORTADORA LTDA",
    cnpj: "47.826.266/0001-51",
    cidade: "Maceió",
    estado: "AL",
    endereco: "Avenida Fernandes Lima, 8, Sala 607 Edif Centenario Office, Farol, Maceió - AL",
    telefone: "(21) 99355-8640",
    email: "carlos.bestway@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A empresa possui diversas filiais e CNAEs, mas o principal é Comércio varejista de artigos de armarinho. O e-mail e telefone foram encontrados em um registro do Inmetro para brinquedos.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MEX TRADE IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "18.588.476/0001-50",
    cidade: "Itapoá",
    estado: "SC",
    endereco: "Rua 2841 Piranduba, 232, Sala 07, Figueira do Pontal, Itapoá - SC",
    telefone: "(47) 2125-4025",
    email: "contato@grupomex.srv.br",
    site: "https://www.grupomex.srv.br/",
    instagram: "https://www.instagram.com/grupomexitajai/",
    segmento: "Trading/Importadora",
    observacao: "A empresa é uma trading/importadora e, embora o CNAE principal seja de vestuário, o Grupo MEX atua com comércio exterior de forma ampla. A NCM 4818.90.90 (tapetes higiênicos) é compatível com a atuação de uma importadora.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "FCM COMERCIO DE MIUDEZAS LTDA",
    cnpj: "23.463.961/0003-08",
    cidade: "ARAQUARI",
    estado: "SC",
    endereco: "ROD BR 280, 1605, GALPAO2 ANEXO A, ITINGA, ARAQUARI - SC",
    telefone: "Não encontrado",
    email: "contato@freitasvarejo.lat",
    site: "https://freitasvarejo.lat/",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ROJEMAC IMPORTACAO E EXPORTACAO LIMITADA",
    cnpj: "03.764.657/0001-13",
    cidade: "Caieiras",
    estado: "SP",
    endereco: "Av. Ádamo Zambelli, 190 - Parque Res. Jordanésia - Caieiras - SP",
    telefone: "(11) 3616-9900",
    email: "cac@gruporojemac.com.br",
    site: "https://www.gruporojemac.com.br/",
    instagram: "@gruporojemac",
    segmento: "Outro",
    observacao: "Importadora de tapetes higiênicos para pets (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "NAPI IMPORT IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "17.815.603/0001-44",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Praca Nsra da Oliveira, 50, Letra A, Pari, São Paulo - SP",
    telefone: "Não encontrado",
    email: "comercialnapi@gmail.com",
    site: "https://napipet.com.br",
    instagram: "@napipet",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "NT FLEX INDUSTRIA E COMERCIO DE ARTIGOS DE TOUCADOR E HIGIENE LTDA",
    cnpj: "04.061.282/0001-98",
    cidade: "Divinópolis",
    estado: "MG",
    endereco: "Rua Pratápolis, 1035, Bom Pastor, Divinópolis - MG",
    telefone: "(37) 3222-1143",
    email: "ntflex@ntflex.com.br",
    site: "http://ntflex.com.br/",
    instagram: "https://www.instagram.com/ntflexoficial/",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "PRONTO IMPORT LTDA",
    cnpj: "36.708.481/0001-31",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Curuca, 442, Vila Maria Baixa, São Paulo - SP",
    telefone: "(11) 94035-8073",
    email: "loja@prontoimport.com",
    site: "Não encontrado",
    instagram: "@pronto_import",
    segmento: "Pet",
    observacao: "A empresa também atua com importação e distribuição de produtos para barbearia. O endereço do CNPJ é em São Paulo, mas o perfil do Facebook indica Guarulhos. Será considerado o endereço do CNPJ.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "HGS COMEX LTDA.",
    cnpj: "53.723.213/0001-08",
    cidade: "DIONÍSIO CERQUEIRA",
    estado: "SC",
    endereco: "AVENIDA PREFEITO ADELINO MANGINI, 575, SALA 02, CENTRO, DIONÍSIO CERQUEIRA - SC, 89950-000",
    telefone: "(49) 9164-2764",
    email: "hgscomex@hgscomex.com.br",
    site: "Não encontrado",
    instagram: "@hgs.comex",
    segmento: "Pet",
    observacao: "Atividade secundária 'Comércio atacadista de alimentos para animais' relevante para produtos pet. O site hgcomex.com.br é de outra empresa.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TRL INTERNACIONAL, IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "14.546.348/0001-93",
    cidade: "Florianópolis",
    estado: "SC",
    endereco: "Rua Professor Ayrton Roberto de Oliveira, 32, Sala 1102 e 1103 Laguna Corporate Center - Itacorubi, Florianopolis - SC, 88.034-050",
    telefone: "(48) 3206-6056",
    email: "contato@trlinternacional.com.br",
    site: "https://www.trlinternacional.com.br/",
    instagram: "@trlinternacionaltrade",
    segmento: "Trading/Importadora",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "W A COMERCIO E DISTRIBUICAO LTDA",
    cnpj: "22.605.343/0001-12",
    cidade: "Santa Luzia",
    estado: "MG",
    endereco: "Avenida das Industrias, 4787, Vila Iris, Santa Luzia - MG, 33.040-130",
    telefone: "(31) 3642-2428",
    email: "comercial@wadistribuidorapet.com.br",
    site: "https://wadistribuidorapet.com.br/",
    instagram: "@wadistribuidorapet",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "VMN BRASIL COMERCIO E DISTRIBUIDORA LTDA",
    cnpj: "49.744.935/0001-71",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    endereco: "Rua Acre, 00051, Sala 705, Centro, Rio de Janeiro - RJ, 20081-000",
    telefone: "(21) 2263-4433",
    email: "contato@vmnbrasil.com.br",
    site: "https://vmnbrasil.com.br/",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "Empresa atua com importação e distribuição de diversos produtos, incluindo higiene pessoal, o que pode abranger tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TURIN TRADING IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "33.389.328/0001-09",
    cidade: "Florianópolis",
    estado: "SC",
    endereco: "Rua Presidente Nereu Ramos, número 69, sala 604 - Bairro Centro, Florianópolis - SC",
    telefone: "(47) 3267-5700",
    email: "turin@turintrading.com.br",
    site: "https://www.turintrading.com.br/",
    instagram: "https://www.instagram.com/turintrading/",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "COPA INDUSTRIAL LTDA",
    cnpj: "02.379.348/0001-67",
    cidade: "BLUMENAU",
    estado: "SC",
    endereco: "R ARNO DELLING, 360, Itoupavazinha, Blumenau - SC",
    telefone: "(47) 3321-9500",
    email: "empresas@copaecia.com.br",
    site: "https://copaeciaempresas.com.br/",
    instagram: "http://www.instagram.com/copaeciaempresas",
    segmento: "Outro",
    observacao: "Não foi encontrada evidência de que a empresa importe tapetes higiênicos para animais de estimação, apesar da informação fornecida na tarefa. As atividades principais e secundárias da empresa estão relacionadas a artigos de uso pessoal e doméstico.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MEGA E-COMMERCE LTDA",
    cnpj: "44.851.499/0001-16",
    cidade: "Ribeirao Preto",
    estado: "SP",
    endereco: "Rua Conselheiro Carrao, 183, Sala 1, Jd Zara, Ribeirao Preto - SP",
    telefone: "(16) 99637-8266",
    email: "contato@petforyoustore.com.br",
    site: "https://www.petforyoustore.com.br",
    instagram: "https://www.instagram.com/petforyoustore",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "FLAMARIMPEX - REPRESENTACOES COMERCIAIS LTDA",
    cnpj: "09.543.616/0001-83",
    cidade: "Criciúma",
    estado: "SC",
    endereco: "Rua Ararangua, 285, Sala 10 - Centro, Criciúma - SC",
    telefone: "(48) 3045-4151",
    email: "comercial@flamarimpex.com.br",
    site: "https://flamarimpex.com.br/",
    instagram: "https://www.instagram.com/flamarimpex/",
    segmento: "Trading/Importadora",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "WHF INDUSTRIA IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "28.184.138/0001-07",
    cidade: "Passo Fundo",
    estado: "RS",
    endereco: "Rua Julio Grandin, 4852, Passo Fundo - RS",
    telefone: "(54) 99931-9755",
    email: "wfindustrialtda@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Empresa atua na fabricação e importação de produtos de higiene, incluindo tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "IGMA COMERCIO SERVICOS E MANUTENCAO LTDA",
    cnpj: "50.310.726/0001-07",
    cidade: "Sorocaba",
    estado: "SP",
    endereco: "Rua Eloa Marisa Goncalves Camargo Alves da Silva, 188, Residencial Jardim Nathalia, Sorocaba - SP",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MINASUL COMPANHIA GERAL DE PRODUTOS LTDA",
    cnpj: "53.194.173/0001-54",
    cidade: "Maceió",
    estado: "AL",
    endereco: "AV CDOR LEAO 1491, Poco, Maceió - AL, 57025-000",
    telefone: "(82) 3027-7670",
    email: "contato@minasulcia.com.br",
    site: "https://minasulcia.com.br/",
    instagram: "@minasul.comercial",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CROSS CONTINENTAL TRADING LTDA",
    cnpj: "48.375.747/0001-50",
    cidade: "Joinville",
    estado: "SC",
    endereco: "Rua Aracaju, 877, Sala 1K, Saguacu, Joinville - SC, 89221-637",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "LEVE MAIS ATACADISTA LTDA",
    cnpj: "47.536.983/0001-49",
    cidade: "Viamão",
    estado: "RS",
    endereco: "Rodovia Rs-118, 7470, Deposito 01, Elsa, Viamão - RS",
    telefone: "(51) 2129-0938",
    email: "FISCAL@ASUN.COM.BR",
    site: "https://www.levemaisonline.com.br/",
    instagram: "https://www.instagram.com/atacado_leve_mais/",
    segmento: "Pet",
    observacao: "Empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "COSTA DISTRIBUIDORA E COMERCIO INTERNACIONAL LTDA",
    cnpj: "54.379.998/0001-06",
    cidade: "Vila Velha",
    estado: "ES",
    endereco: "Rua Inacio Higino, 673, Sala 909, Praia da Costa, Vila Velha - ES",
    telefone: "(27) 3020-0000",
    email: "comercial@costaimportacao.com.br",
    site: "https://costaimportacao.com.br/",
    instagram: "https://www.instagram.com/costaimportacao/",
    segmento: "Trading/Importadora",
    observacao: "Empresa importadora de produtos alimentícios, incluindo azeites, pescados e especiarias. O telefone e e-mail foram obtidos do site oficial da empresa.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "AVANTE COMERCIO DE PRODUTOS EM GERAL LTDA",
    cnpj: "54.541.155/0001-64",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Etelvina, 182, Vila Feliz, São Paulo - SP",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ELEVEN COMERCIO LTDA",
    cnpj: "14.380.494/0001-91",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Rua Uruguai, 161, Sala 402, Ed. Unique, Centro, Itajaí, SC, Brasil – 88302-201",
    telefone: "(47) 3046-6333",
    email: "contato@elevengrp.com",
    site: "https://elevengrp.com",
    instagram: "https://www.instagram.com/elevengrp_",
    segmento: "Trading/Importadora",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "LUXOR COMERCIO INTERNACIONAL LTDA",
    cnpj: "09.527.978/0001-80",
    cidade: "FLORIANOPOLIS",
    estado: "SC",
    endereco: "RUA SOUZA DUTRA, 145 - SALA: 711, ESTREITO, FLORIANOPOLIS - SC",
    telefone: "(48) 3030-9900",
    email: "contato@luxortrade.com.br",
    site: "http://www.luxortrade.com.br/",
    instagram: "@luxortrade",
    segmento: "Trading/Importadora",
    observacao: "Empresa especializada em operações de comércio exterior, importação e exportação. Não foi encontrada menção específica sobre importação de tapetes higiênicos para pets (NCM 4818.90.90) no site oficial.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MARGARETH BERTONI GHUNEIM LTDA",
    cnpj: "22.714.080/0001-80",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Teresina, 346 - Vila Bertioga, São Paulo - SP",
    telefone: "(11) 2603-4050",
    email: "francisco@kfw.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "O segmento principal é Comércio atacadista de embalagens. O telefone e e-mail encontrados são da filial (CNPJ 22.714.080/0002-60).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "LDX COMERCIO E IMPORTACAO LTDA",
    cnpj: "60.615.137/0001-82",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Rua Samuel Heusi, 463, Sala 402 Box 528, Centro, Itajaí - SC",
    telefone: "(42) 9972-4111",
    email: "ldxcomercio1@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Empresa fundada em 30/04/2025 e com situação cadastral Ativa.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "PREMIER TRADE COMERCIO IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "10.673.864/0001-28",
    cidade: "Itapema",
    estado: "SC",
    endereco: "Rua 454, nº 10, Sala 2, Morretes, Itapema - SC",
    telefone: "(47) 3345-3000",
    email: "contato@premiertrade.com.br",
    site: "https://premier.com.vc/",
    instagram: "https://www.instagram.com/premiertrade.br/",
    segmento: "Trading/Importadora",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CARAVAN DO BRASIL TRADING LTDA",
    cnpj: "20.403.699/0001-48",
    cidade: "Balneário Camboriú",
    estado: "SC",
    endereco: "Avenida Terceira Avenida, 1145, Sala 21 - Centro, Balneario Camboriu - SC",
    telefone: "(47) 2122-6889",
    email: "sac@caravandobrasil.com.br",
    site: "https://www.caravandobrasil.com.br/",
    instagram: "https://www.instagram.com/caravandobrasil/",
    segmento: "Trading/Importadora",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "LION IMPORT COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "42.900.397/0001-18",
    cidade: "ITAJAI",
    estado: "SC",
    endereco: "RUA CONEGO THOMAZ FONTES, 145, SALA 1505 ANDAR 15, CENTRO, ITAJAI - SC",
    telefone: "Não encontrado",
    email: "MAURICIOLIMA@LIVE.IE",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ALPHA YNFINITY COMERCIO INTERNACIONAL LTDA",
    cnpj: "48.218.557/0001-20",
    cidade: "Itajai",
    estado: "SC",
    endereco: "R FRANCISCO REIS 1402 SALA 7 AE, Cordeiros, Itajai - SC",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Atacado",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "FLASH IMPORTADORA, COMERCIO ATACADISTA DE VARIEDADES LTDA",
    cnpj: "44.276.591/0001-08",
    cidade: "ITAJAI",
    estado: "SC",
    endereco: "R AGOSTINHO FERNANDES VIEIRA 62 SALA 502, Fazenda, Itajai - SC",
    telefone: "(49) 2000-4110",
    email: "lourenco4110@outlook.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Atividade principal: Comércio atacadista de outros equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente. Fundada em 17/11/2021.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DALE LOG COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "29.174.922/0001-05",
    cidade: "ITAJAI",
    estado: "SC",
    endereco: "RUA LAURO MULLER, 655, SALA 206, FAZENDA, ITAJAI - SC",
    telefone: "(48) 3411-5810",
    email: "COMERCIAL@DALELOG.COM.BR",
    site: "https://dalelog.com.br/",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "A empresa se apresenta como importadora de alimentos (queijos, azeites, etc.) e não há evidências diretas de importação de tapetes higiênicos para pets (NCM 4818.90.90) nas fontes consultadas.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "GENESIS IMPORTS COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "19.714.516/0002-07",
    cidade: "CABO DE SANTO AGOSTINHO",
    estado: "PE",
    endereco: "RODOVIA BR 101 SUL, KM 96,4, 5225, DISTRITO INDUSTRIAL DIPER, CABO DE SANTO AGOSTINHO - PE",
    telefone: "(81) 3204-4365",
    email: "info@GenesisImports.com.br",
    site: "https://genesisimports.com.br/",
    instagram: "https://www.instagram.com/genesis_imports/",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DROMOS COMERCIAL IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "17.184.970/0003-59",
    cidade: "SAO PAULO",
    estado: "SP",
    endereco: "AV PAULISTA 171 SALA 299 A PAVM, Bela Vista, Sao Paulo - SP",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "https://www.dromos.com.br/",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "Empresa com situação cadastral BAIXADA.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ALIANCA COMERCIO ATACADISTA LTDA",
    cnpj: "00.506.346/0001-66",
    cidade: "Uberlândia",
    estado: "MG",
    endereco: "Av. Afonso Pena, 3385, Uberlândia - MG",
    telefone: "(34) 3233-9000",
    email: "contato@aliancaatacadista.com.br",
    site: "https://www.aliancaatacado.com.br/",
    instagram: "https://www.instagram.com/aliancaatacadista_/",
    segmento: "Atacado",
    observacao: "Não foi possível confirmar a importação de tapetes higiênicos para pets, nem encontrar informações específicas sobre produtos pet no catálogo.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "SLIME IMPORT LTDA",
    cnpj: "49.122.445/0001-33",
    cidade: "Maceió",
    estado: "AL",
    endereco: "Rua Rivadavia Carnauba, 112, Sala 16, Pinheiro, Maceio - AL",
    telefone: "(82) 3241-1988",
    email: "igor@slimeimport.com.br",
    site: "https://slimeimport.com.br/",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "20 COMERCIAL DE UTILIDADES DOMESTICAS LTDA",
    cnpj: "06.142.807/0001-45",
    cidade: "Guarulhos",
    estado: "SP",
    endereco: "AV JUSTINO DE MAIO 396, Cidade Industrial S, Guarulhos - SP, 07222-000",
    telefone: "(11) 3312-3680",
    email: "legal@contabs.com.br",
    site: "https://www.newgoods.com.br",
    instagram: "@20.comercial",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "BRAKEY COMERCIO DE PRODUTOS DE HIGIENE LTDA",
    cnpj: "15.462.217/0001-90",
    cidade: "SÃO PAULO",
    estado: "SP",
    endereco: "AVENIDA PEDROSO DE MORAIS, 517, 7 ANDAR CJ 74, PINHEIROS, SÃO PAULO - SP",
    telefone: "(11) 3095-9600",
    email: "comercial@brakey.com.br",
    site: "https://www.brakey.com.br",
    instagram: "https://www.instagram.com/brakeyequip/",
    segmento: "Pet",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil, conforme instrução da tarefa. O site oficial foca em produtos de higiene para uso comercial/corporativo.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "BRING IMPORT LTDA",
    cnpj: "40.896.798/0001-16",
    cidade: "Joinville",
    estado: "SC",
    endereco: "Avenida Rolf Wiest, 277, Sala 509 e 511 - Bom Retiro, Joinville - SC, 89.223-005",
    telefone: "(47) 3307-9119",
    email: "BRING@BRINGIMPORT.COM.BR",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A atividade principal da empresa é Comércio por atacado de peças e acessórios para motocicletas e motonetas. Não há indícios de importação de tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "D&A DECORACAO E AMBIENTACAO LTDA",
    cnpj: "08.749.430/0002-01",
    cidade: "Recife",
    estado: "PE",
    endereco: "R. Riachão, 807 – 3A, 4A, 5A, 12A, 14A, Muribeca, Recife - PE, CEP 54.355-057",
    telefone: "(81) 2125-5990",
    email: "relacionamento@florarte.com.br",
    site: "https://deadecoracao.com.br/",
    instagram: "@deadecoracao",
    segmento: "Outro",
    observacao: "A empresa atua com decoração, plantas permanentes, utilidades domésticas e artigos para casa. Embora o site não mencione explicitamente tapetes higiênicos para pets, a tarefa indica que a empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CASARAO DO E-COMMERCE LTDA",
    cnpj: "60.139.713/0001-62",
    cidade: "Valinhos",
    estado: "SP",
    endereco: "Rua Nicolau Vinicius Parodi, 705 - Jardim Monte Verde, Valinhos - SP",
    telefone: "(19) 99193-8012",
    email: "casaraodoecommerce@gmail.com",
    site: "https://www.casaraodoecommerce.com.br",
    instagram: "@casaraodoecommerce",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CLINK COMERCIO DE IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "97.534.530/0001-51",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Avenida Sen Queiros, 302, Conj 1201 - Centro, São Paulo - SP",
    telefone: "(11) 97160-5803",
    email: "beatriz@clinkimport.com",
    site: "https://clinkimport.com/",
    instagram: "https://www.instagram.com/clink.utilidades/",
    segmento: "Trading/Importadora",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "H & W TRADING IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "24.989.827/0001-38",
    cidade: "Recife",
    estado: "PE",
    endereco: "Avenida Marquês de Olinda, 200 Sala 310 - Recife Antigo, Recife - PE",
    telefone: "(81) 3877-3631",
    email: "contato@hwtrading.com.br",
    site: "https://hwtrading.com.br/",
    instagram: "https://www.instagram.com/hw.trading/",
    segmento: "Trading/Importadora",
    observacao: "Empresa de importação e exportação, com foco em mercados internacionais.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "UPPER TRADE IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "11.599.956/0001-78",
    cidade: "Brusque",
    estado: "SC",
    endereco: "Rodovia Ivo Silveira SC-108, 7970, Volta Grande, Brusque - SC",
    telefone: "(47) 3350-6102",
    email: "contato4@grupoupper.com.br",
    site: "https://grupoupper.com.br/",
    instagram: "@uppertrade",
    segmento: "Trading/Importadora",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil. O site da Upper Trade está em manutenção.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DE MACEDO FONSECA LTDA",
    cnpj: "60.449.919/0001-99",
    cidade: "Osasco",
    estado: "SP",
    endereco: "Rua Manoel Saraiva, 45, Apt 1309, Vila Campesina, Osasco - SP, 06023-060",
    telefone: "(11) 94230-5038",
    email: "pequenogenio1994@gmail.com",
    site: "https://www.pequenogenio.com.br/",
    instagram: "https://www.instagram.com/pequenogenio1994/",
    segmento: "Outro",
    observacao: "Empresa de educação infantil, não importa tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "NOVO SECULO IMPORTACAO EXPORTACAO E COMERCIO LTDA",
    cnpj: "09.595.599/0001-28",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    endereco: "Rua Bittencourt Sampaio, 230 Supl.188, Ramos, Rio de Janeiro - RJ",
    telefone: "(21) 98132-0112",
    email: "daniel@novoseculo.net.br",
    site: "Não encontrado",
    instagram: "@novoseculoimp",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DM8 COMERCIO E SERVICOS LTDA",
    cnpj: "10.398.382/0001-07",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua do Bosque, 1484, Andar 13 Sala 1316/17/18/19 - Barra Funda, São Paulo - SP",
    telefone: "(11) 3939-0888",
    email: "FISCAL@DM8.COM.BR",
    site: "https://dm8.com.br/",
    instagram: "https://www.instagram.com/dm8comex/",
    segmento: "Trading/Importadora",
    observacao: "Consultoria em Comércio Exterior habilitada no SISCOMEX (RADAR) para operações de Importação e Exportação.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DOMESTIX COMERCIO LTDA",
    cnpj: "40.234.618/0001-30",
    cidade: "SAO PAULO",
    estado: "SP",
    endereco: "Rua Dr Valentim Boucas, 602 - Vila Mazzei, Sao Paulo - SP, 02.315-010",
    telefone: "(11) 99557-7710",
    email: "WORLDGLOBALECOM@GMAIL.COM",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Comércio varejista de outros artigos de uso doméstico não especificados anteriormente. Não foi possível confirmar a importação de tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MRD IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "30.961.647/0001-40",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Av.: Cel. Marcos Konder, 1207 sala 81 centro, Itajaí-SC, 88.301-303",
    telefone: "(47) 99977-7799",
    email: "contato@mrdtrading.com.br",
    site: "https://mrdtrading.com.br/",
    instagram: "Não encontrado",
    segmento: "Higiene Hospitalar",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "DJW COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "14.659.359/0001-80",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Mario Enzio Pasqualucci, 121, Vila São Francisco (Zona Sul), São Paulo - SP, 04711-090",
    telefone: "(11) 5182-2913",
    email: "sac@sekich.com.br",
    site: "https://sekich.com.br/",
    instagram: "https://www.instagram.com/sekich_brasil",
    segmento: "Outro",
    observacao: "A empresa importa tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "BUENO IMPORTADORA E EXPORTADORA LTDA",
    cnpj: "51.102.324/0001-71",
    cidade: "Itatiba",
    estado: "SP",
    endereco: "Rua Adelino Gasparine, 375, Jd Verona, Itatiba - SP",
    telefone: "(11) 99961-4475",
    email: "bueno@buenocreative.com.br",
    site: "https://www.buenocreative.com.br",
    instagram: "@buenoimportadora",
    segmento: "Trading/Importadora",
    observacao: "Empresa atua com importação direta e compartilhada, oferecendo consultoria e habilitação no RADAR Siscomex.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "SECCON INDUSTRIA COMERCIO LTDA",
    cnpj: "04.506.658/0001-20",
    cidade: "JUNDIAÍ",
    estado: "SP",
    endereco: "Avenida Olivio Roncoletta, 465, Galpao09, Vila Hortolandia, Jundiaí - SP",
    telefone: "(11) 5583-5583",
    email: "contato@seccon.com.br",
    site: "https://seccon.com.br/",
    instagram: "@seccon.br",
    segmento: "Outro",
    observacao: "A empresa atua no segmento de conectores, cabos e telecomunicações, não importando tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "FONTEBRAS COMERCIO DE PRESENTES LTDA",
    cnpj: "13.250.332/0001-76",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Rua Came, 196, Mooca, São Paulo - SP",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "@fontebras",
    segmento: "Outro",
    observacao: "A atividade principal da empresa é comércio atacadista de artigos do vestuário e acessórios, não havendo evidências de importação de tapetes higiênicos para pets (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "JRF IMPORTS COMERCIAL LTDA",
    cnpj: "17.221.991/0001-35",
    cidade: "Caconde",
    estado: "SP",
    endereco: "AVEN JOSE SEBASTIAO REMEDIO 95, Varzea, Caconde - SP",
    telefone: "(19) 3662-3248",
    email: "junior@foiliaimports.com.br",
    site: "Não encontrado",
    instagram: "https://www.instagram.com/folia_imports/",
    segmento: "Pet",
    observacao: "A empresa também é conhecida como Folia Imports. Possui um escritório/showroom em São Paulo, SP, com outro telefone e e-mail de contato.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "ASN BRASIL IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "20.966.942/0001-36",
    cidade: "Cotia",
    estado: "SP",
    endereco: "Rua Adib Auada, 35, Cond Prime Office Park Conj 311 Bloco a, Jd Lambreta, Cotia - SP, 06710-700",
    telefone: "(11) 4195-5425",
    email: "elisangela@asnindustria.com.br",
    site: "https://www.dilcintia.com.br/",
    instagram: "https://www.instagram.com/dilcintia.beauty/",
    segmento: "Outro",
    observacao: "A empresa é matriz da marca Dilcintia Beauty, especializada em instrumentos de cutelaria e beleza. Não foi encontrada confirmação direta sobre a importação de tapetes higiênicos para pets, mas a atividade principal é genérica e o NCM 4818.90.90 (outros artigos de papel para higiene e hospitalar) é relevante.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "NEPTUNE 8 IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "14.414.005/0001-75",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Avenida Nilo Bittencourt, 306 - Sao Vicente, Itajaí - SC",
    telefone: "(47) 8805-1591",
    email: "financeiro02.proaction@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "T. GLOBO IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "15.135.338/0001-28",
    cidade: "ITAJAI",
    estado: "SC",
    endereco: "RUA PEDRO FERREIRA 333, SALA 1404 A ANDAR 14, CENTRO, ITAJAI - SC",
    telefone: "(11) 3034-3475",
    email: "comercial@globoimport.com.br",
    site: "https://globoimport.com.br/",
    instagram: "https://www.instagram.com/globoimport_",
    segmento: "Trading/Importadora",
    observacao: "A empresa também possui uma filial em São Paulo (CNPJ 15.135.338/0012-80) e atua na importação de tapetes higiênicos para animais de estimação (NCM 4818.90.90).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TRAIDEX - COMERCIO IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "45.113.500/0001-78",
    cidade: "Vila Velha",
    estado: "ES",
    endereco: "RUA PEDRO PALACIOS 79 EDIF C. JURID DE V. VELHASALA, Centro, Vila Velha - ES",
    telefone: "(27) 99811-480",
    email: "traidex@traidex.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Trading/Importadora, Pet",
    observacao: "O telefone e e-mail encontrados são da filial em Maceió, mas podem ser usados como contato geral. A matriz está localizada em Vila Velha, ES.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "LIVE LASH IMPORTACAO LTDA",
    cnpj: "47.360.385/0001-61",
    cidade: "Campinas",
    estado: "SP",
    endereco: "Rua Antonio Guimaraes, 41 - Botafogo, Campinas - SP",
    telefone: "(19) 99359-9448",
    email: "welashstore@gmail.com",
    site: "https://livelash.com.br/",
    instagram: "@livelashoficial",
    segmento: "Cosméticos e Acessórios de Beleza",
    observacao: "Apesar da solicitação inicial mencionar importação de tapetes higiênicos para pets, a pesquisa indica que o foco principal da empresa é a importação de cílios e acessórios de beleza.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "CURY COMERCIO, IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "12.065.480/0001-58",
    cidade: "Guarulhos",
    estado: "SP",
    endereco: "Avenida Jaguarao, 325, Cidade Industrial Satelite de Sao Paulo, Guarulhos - SP",
    telefone: "(11) 2612-1550",
    email: "sac@partiufestaimportadora.com.br",
    site: "https://partiufestaimportadora.com.br/",
    instagram: "https://www.instagram.com/partiufesta.importadora/",
    segmento: "Outro",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90). Atua também com artigos para festas.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "MAXIMO IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "60.496.514/0001-01",
    cidade: "Macapá",
    estado: "AP",
    endereco: "Rua Candido Mendes, 1516, Sala 06, Central, Macapá - AP",
    telefone: "(13) 9209-3553",
    email: "gelsonsilvadeoliveirasv@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "BBI DISTRIBUIDORA DE ARTIGOS DIVERSOS LTDA",
    cnpj: "50.190.665/0001-83",
    cidade: "Flores da Cunha",
    estado: "RS",
    endereco: "Travessa Felisberto da Silva, Flores da Cunha - RS, 95.270-000",
    telefone: "(54) 99900-3297",
    email: "bbidistribuidoradeartigos@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Atividade principal: Comércio atacadista de outros equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente. Atividade secundária: Comércio atacadista de produtos de higiene pessoal.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TOTALL VERSE IMPORTACAO E COMERCIO LTDA",
    cnpj: "13.105.990/0001-74",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Avenida Do Cafe, 238, Sala 201, Vila Guarani (Z Sul), São Paulo - SP",
    telefone: "(11) 3229-4943",
    email: "helen@totallverse.com.br",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Importa tapetes higiênicos para animais de estimação (NCM 4818.90.90) da China para o Brasil.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "EURO-X IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "56.605.302/0001-48",
    cidade: "CARUARU",
    estado: "PE",
    endereco: "AV ADJAR DA SILVA CASE, 800 - SALA 03 6 PISO CARUARU CORPORATE, INDIANÓPOLIS, CARUARU - PE",
    telefone: "(81) 3319-8491",
    email: "CONTATO@EUROXCOMERCIOEXTERIOR.COM.BR",
    site: "Não encontrado",
    instagram: "@euroxgroup",
    segmento: "Pet",
    observacao: "O CNAE principal da empresa é \"Comércio atacadista de bolsas, malas e artigos de viagem\", mas há fortes indícios de atuação no segmento pet com tapetes higiênicos, possivelmente como importadora da marca \"Euro Pet\" ou \"Euro Home\". A empresa foi fundada recentemente (13/08/2024).",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "OPEN TRADE EXPORTACAO E IMPORTACAO LTDA",
    cnpj: "07.104.810/0001-37",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Av. Osvaldo Reis, 2470 - 1° andar - Santa Clara, Itajaí - SC",
    telefone: "(47) 3404-4400",
    email: "contato@opentrade.com.br",
    site: "https://opentrade.com.br/",
    instagram: "https://www.instagram.com/opentradecomex/",
    segmento: "Trading/Importadora",
    observacao: "Especialista em comércio exterior, importação e exportação, com foco em redução de custos, previsibilidade e segurança nas operações.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "RLG DO BRASIL DISTRIBUICAO E VAREJO LTDA",
    cnpj: "49.943.533/0001-04",
    cidade: "São Paulo",
    estado: "SP",
    endereco: "Avenida Dr Cardoso de Melo, 1184, Andar 17 Conj 171 e 172, Vila Olimpia, São Paulo - SP, 04548-004",
    telefone: "(11) 3106-4433",
    email: "nfecte@richemont.com",
    site: "https://www.richemont.com/",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "A empresa atua no setor de joalherias e artigos de luxo, não havendo indícios de importação de tapetes higiênicos para pets.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "RDR IMPORTACAO E EXPORTACAO LTDA",
    cnpj: "44.490.369/0001-03",
    cidade: "Itajaí",
    estado: "SC",
    endereco: "Rua Pedro Ferreira, 155 Sala 1700A, Centro, Itajaí - SC",
    telefone: "(47) 3405-0730",
    email: "rdrimportacao@gmail.com",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Pet",
    observacao: "Empresa fundada em 06/12/2021. Atividade principal: Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "AZUL IMPORTACAO LTDA",
    cnpj: "52.348.321/0001-85",
    cidade: "Apiúna",
    estado: "SC",
    endereco: "Rodovia Br 470, 5655, Apiuna - SC, 89.135-000",
    telefone: "(47) 4141-3030",
    email: "compreazul@outlook.com",
    site: "Não encontrado",
    instagram: "@azulimportacao",
    segmento: "Pet",
    observacao: "Não encontrado",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
  {
    nome: "TRANSO COMERCIO E IMPORTACAO LTDA",
    cnpj: "Não encontrado",
    cidade: "Não encontrado",
    estado: "Não encontrado",
    endereco: "Não encontrado",
    telefone: "Não encontrado",
    email: "Não encontrado",
    site: "Não encontrado",
    instagram: "Não encontrado",
    segmento: "Outro",
    observacao: "Não foram encontradas informações específicas sobre a empresa TRANSO COMERCIO E IMPORTACAO LTDA como importadora de tapetes higiênicos para pets no Brasil através de buscas públicas.",
    fobUsd: 0,
    percentual: 0,
    pesoKg: 0,
  },
];
